#light
module SilverlightSecurityVerifier.Patterns

#nowarn "57"
open System
open System.Reflection
open System.Reflection.Emit
open System.Collections.Generic

open SilverlightSecurityVerifier.Reflection

let (|Add|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 88s) then Some(o.OpCode, o.Operand) else None
let (|AddOvf|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 214s) then Some(o.OpCode, o.Operand) else None
let (|AddOvfUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 215s) then Some(o.OpCode, o.Operand) else None
let (|And|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 95s) then Some(o.OpCode, o.Operand) else None
let (|Arglist|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -512s) then Some(o.OpCode, o.Operand) else None
let (|Beq|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 59s) then Some(o.OpCode, o.Operand) else None
let (|BeqS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 46s) then Some(o.OpCode, o.Operand) else None
let (|Bge|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 60s) then Some(o.OpCode, o.Operand) else None
let (|BgeS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 47s) then Some(o.OpCode, o.Operand) else None
let (|BgeUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 65s) then Some(o.OpCode, o.Operand) else None
let (|BgeUnS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 52s) then Some(o.OpCode, o.Operand) else None
let (|Bgt|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 61s) then Some(o.OpCode, o.Operand) else None
let (|BgtS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 48s) then Some(o.OpCode, o.Operand) else None
let (|BgtUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 66s) then Some(o.OpCode, o.Operand) else None
let (|BgtUnS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 53s) then Some(o.OpCode, o.Operand) else None
let (|Ble|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 62s) then Some(o.OpCode, o.Operand) else None
let (|BleS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 49s) then Some(o.OpCode, o.Operand) else None
let (|BleUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 67s) then Some(o.OpCode, o.Operand) else None
let (|BleUnS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 54s) then Some(o.OpCode, o.Operand) else None
let (|Blt|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 63s) then Some(o.OpCode, o.Operand) else None
let (|BltS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 50s) then Some(o.OpCode, o.Operand) else None
let (|BltUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 68s) then Some(o.OpCode, o.Operand) else None
let (|BltUnS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 55s) then Some(o.OpCode, o.Operand) else None
let (|BneUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 64s) then Some(o.OpCode, o.Operand) else None
let (|BneUnS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 51s) then Some(o.OpCode, o.Operand) else None
let (|Box|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 140s) then Some(o.OpCode, o.Operand) else None
let (|Br|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 56s) then Some(o.OpCode, o.Operand) else None
let (|BrS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 43s) then Some(o.OpCode, o.Operand) else None
let (|Break|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 1s) then Some(o.OpCode, o.Operand) else None
let (|Brfalse|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 57s) then Some(o.OpCode, o.Operand) else None
let (|BrfalseS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 44s) then Some(o.OpCode, o.Operand) else None
let (|Brtrue|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 58s) then Some(o.OpCode, o.Operand) else None
let (|BrtrueS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 45s) then Some(o.OpCode, o.Operand) else None
let (|Call|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 40s) then Some(o.OpCode, o.Operand) else None
let (|Calli|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 41s) then Some(o.OpCode, o.Operand) else None
let (|Callvirt|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 111s) then Some(o.OpCode, o.Operand) else None
let (|Castclass|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 116s) then Some(o.OpCode, o.Operand) else None
let (|Ceq|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -511s) then Some(o.OpCode, o.Operand) else None
let (|Cgt|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -510s) then Some(o.OpCode, o.Operand) else None
let (|CgtUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -509s) then Some(o.OpCode, o.Operand) else None
let (|Ckfinite|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 195s) then Some(o.OpCode, o.Operand) else None
let (|Clt|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -508s) then Some(o.OpCode, o.Operand) else None
let (|CltUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -507s) then Some(o.OpCode, o.Operand) else None
let (|Constrained|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -490s) then Some(o.OpCode, o.Operand) else None
let (|ConvI|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 211s) then Some(o.OpCode, o.Operand) else None
let (|ConvI1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 103s) then Some(o.OpCode, o.Operand) else None
let (|ConvI2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 104s) then Some(o.OpCode, o.Operand) else None
let (|ConvI4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 105s) then Some(o.OpCode, o.Operand) else None
let (|ConvI8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 106s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfI|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 212s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfIUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 138s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfI1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 179s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfI1Un|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 130s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfI2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 181s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfI2Un|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 131s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfI4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 183s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfI4Un|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 132s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfI8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 185s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfI8Un|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 133s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfU|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 213s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfUUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 139s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfU1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 180s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfU1Un|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 134s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfU2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 182s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfU2Un|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 135s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfU4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 184s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfU4Un|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 136s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfU8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 186s) then Some(o.OpCode, o.Operand) else None
let (|ConvOvfU8Un|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 137s) then Some(o.OpCode, o.Operand) else None
let (|ConvRUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 118s) then Some(o.OpCode, o.Operand) else None
let (|ConvR4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 107s) then Some(o.OpCode, o.Operand) else None
let (|ConvR8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 108s) then Some(o.OpCode, o.Operand) else None
let (|ConvU|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 224s) then Some(o.OpCode, o.Operand) else None
let (|ConvU1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 210s) then Some(o.OpCode, o.Operand) else None
let (|ConvU2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 209s) then Some(o.OpCode, o.Operand) else None
let (|ConvU4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 109s) then Some(o.OpCode, o.Operand) else None
let (|ConvU8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 110s) then Some(o.OpCode, o.Operand) else None
let (|Cpblk|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -489s) then Some(o.OpCode, o.Operand) else None
let (|Cpobj|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 112s) then Some(o.OpCode, o.Operand) else None
let (|Div|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 91s) then Some(o.OpCode, o.Operand) else None
let (|DivUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 92s) then Some(o.OpCode, o.Operand) else None
let (|Dup|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 37s) then Some(o.OpCode, o.Operand) else None
let (|Endfilter|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -495s) then Some(o.OpCode, o.Operand) else None
let (|Endfinally|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 220s) then Some(o.OpCode, o.Operand) else None
let (|Initblk|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -488s) then Some(o.OpCode, o.Operand) else None
let (|Initobj|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -491s) then Some(o.OpCode, o.Operand) else None
let (|Isinst|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 117s) then Some(o.OpCode, o.Operand) else None
let (|Jmp|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 39s) then Some(o.OpCode, o.Operand) else None
let (|Ldarg|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -503s) then Some(o.OpCode, o.Operand) else None
let (|Ldarg0|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 2s) then Some(o.OpCode, o.Operand) else None
let (|Ldarg1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 3s) then Some(o.OpCode, o.Operand) else None
let (|Ldarg2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 4s) then Some(o.OpCode, o.Operand) else None
let (|Ldarg3|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 5s) then Some(o.OpCode, o.Operand) else None
let (|LdargS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 14s) then Some(o.OpCode, o.Operand) else None
let (|Ldarga|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -502s) then Some(o.OpCode, o.Operand) else None
let (|LdargaS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 15s) then Some(o.OpCode, o.Operand) else None
let (|LdcI4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 32s) then Some(o.OpCode, o.Operand) else None
let (|LdcI40|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 22s) then Some(o.OpCode, o.Operand) else None
let (|LdcI41|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 23s) then Some(o.OpCode, o.Operand) else None
let (|LdcI42|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 24s) then Some(o.OpCode, o.Operand) else None
let (|LdcI43|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 25s) then Some(o.OpCode, o.Operand) else None
let (|LdcI44|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 26s) then Some(o.OpCode, o.Operand) else None
let (|LdcI45|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 27s) then Some(o.OpCode, o.Operand) else None
let (|LdcI46|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 28s) then Some(o.OpCode, o.Operand) else None
let (|LdcI47|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 29s) then Some(o.OpCode, o.Operand) else None
let (|LdcI48|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 30s) then Some(o.OpCode, o.Operand) else None
let (|LdcI4M1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 21s) then Some(o.OpCode, o.Operand) else None
let (|LdcI4S|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 31s) then Some(o.OpCode, o.Operand) else None
let (|LdcI8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 33s) then Some(o.OpCode, o.Operand) else None
let (|LdcR4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 34s) then Some(o.OpCode, o.Operand) else None
let (|LdcR8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 35s) then Some(o.OpCode, o.Operand) else None
let (|Ldelem|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 163s) then Some(o.OpCode, o.Operand) else None
let (|LdelemI|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 151s) then Some(o.OpCode, o.Operand) else None
let (|LdelemI1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 144s) then Some(o.OpCode, o.Operand) else None
let (|LdelemI2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 146s) then Some(o.OpCode, o.Operand) else None
let (|LdelemI4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 148s) then Some(o.OpCode, o.Operand) else None
let (|LdelemI8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 150s) then Some(o.OpCode, o.Operand) else None
let (|LdelemR4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 152s) then Some(o.OpCode, o.Operand) else None
let (|LdelemR8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 153s) then Some(o.OpCode, o.Operand) else None
let (|LdelemRef|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 154s) then Some(o.OpCode, o.Operand) else None
let (|LdelemU1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 145s) then Some(o.OpCode, o.Operand) else None
let (|LdelemU2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 147s) then Some(o.OpCode, o.Operand) else None
let (|LdelemU4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 149s) then Some(o.OpCode, o.Operand) else None
let (|Ldelema|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 143s) then Some(o.OpCode, o.Operand) else None
let (|Ldfld|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 123s) then Some(o.OpCode, o.Operand) else None
let (|Ldflda|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 124s) then Some(o.OpCode, o.Operand) else None
let (|Ldftn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -506s) then Some(o.OpCode, o.Operand) else None
let (|LdindI|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 77s) then Some(o.OpCode, o.Operand) else None
let (|LdindI1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 70s) then Some(o.OpCode, o.Operand) else None
let (|LdindI2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 72s) then Some(o.OpCode, o.Operand) else None
let (|LdindI4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 74s) then Some(o.OpCode, o.Operand) else None
let (|LdindI8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 76s) then Some(o.OpCode, o.Operand) else None
let (|LdindR4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 78s) then Some(o.OpCode, o.Operand) else None
let (|LdindR8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 79s) then Some(o.OpCode, o.Operand) else None
let (|LdindRef|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 80s) then Some(o.OpCode, o.Operand) else None
let (|LdindU1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 71s) then Some(o.OpCode, o.Operand) else None
let (|LdindU2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 73s) then Some(o.OpCode, o.Operand) else None
let (|LdindU4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 75s) then Some(o.OpCode, o.Operand) else None
let (|Ldlen|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 142s) then Some(o.OpCode, o.Operand) else None
let (|Ldloc|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -500s) then Some(o.OpCode, o.Operand) else None
let (|Ldloc0|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 6s) then Some(o.OpCode, o.Operand) else None
let (|Ldloc1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 7s) then Some(o.OpCode, o.Operand) else None
let (|Ldloc2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 8s) then Some(o.OpCode, o.Operand) else None
let (|Ldloc3|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 9s) then Some(o.OpCode, o.Operand) else None
let (|LdlocS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 17s) then Some(o.OpCode, o.Operand) else None
let (|Ldloca|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -499s) then Some(o.OpCode, o.Operand) else None
let (|LdlocaS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 18s) then Some(o.OpCode, o.Operand) else None
let (|Ldnull|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 20s) then Some(o.OpCode, o.Operand) else None
let (|Ldobj|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 113s) then Some(o.OpCode, o.Operand) else None
let (|Ldsfld|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 126s) then Some(o.OpCode, o.Operand) else None
let (|Ldsflda|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 127s) then Some(o.OpCode, o.Operand) else None
let (|Ldstr|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 114s) then Some(o.OpCode, o.Operand) else None
let (|Ldtoken|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 208s) then Some(o.OpCode, o.Operand) else None
let (|Ldvirtftn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -505s) then Some(o.OpCode, o.Operand) else None
let (|Leave|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 221s) then Some(o.OpCode, o.Operand) else None
let (|LeaveS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 222s) then Some(o.OpCode, o.Operand) else None
let (|Localloc|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -497s) then Some(o.OpCode, o.Operand) else None
let (|Mkrefany|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 198s) then Some(o.OpCode, o.Operand) else None
let (|Mul|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 90s) then Some(o.OpCode, o.Operand) else None
let (|MulOvf|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 216s) then Some(o.OpCode, o.Operand) else None
let (|MulOvfUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 217s) then Some(o.OpCode, o.Operand) else None
let (|Neg|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 101s) then Some(o.OpCode, o.Operand) else None
let (|Newarr|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 141s) then Some(o.OpCode, o.Operand) else None
let (|Newobj|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 115s) then Some(o.OpCode, o.Operand) else None
let (|Nop|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 0s) then Some(o.OpCode, o.Operand) else None
let (|Not|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 102s) then Some(o.OpCode, o.Operand) else None
let (|Or|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 96s) then Some(o.OpCode, o.Operand) else None
let (|Pop|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 38s) then Some(o.OpCode, o.Operand) else None
let (|Prefix1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 254s) then Some(o.OpCode, o.Operand) else None
let (|Prefix2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 253s) then Some(o.OpCode, o.Operand) else None
let (|Prefix3|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 252s) then Some(o.OpCode, o.Operand) else None
let (|Prefix4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 251s) then Some(o.OpCode, o.Operand) else None
let (|Prefix5|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 250s) then Some(o.OpCode, o.Operand) else None
let (|Prefix6|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 249s) then Some(o.OpCode, o.Operand) else None
let (|Prefix7|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 248s) then Some(o.OpCode, o.Operand) else None
let (|Prefixref|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 255s) then Some(o.OpCode, o.Operand) else None
let (|Readonly|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -482s) then Some(o.OpCode, o.Operand) else None
let (|Refanytype|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -483s) then Some(o.OpCode, o.Operand) else None
let (|Refanyval|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 194s) then Some(o.OpCode, o.Operand) else None
let (|Rem|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 93s) then Some(o.OpCode, o.Operand) else None
let (|RemUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 94s) then Some(o.OpCode, o.Operand) else None
let (|Ret|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 42s) then Some(o.OpCode, o.Operand) else None
let (|Rethrow|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -486s) then Some(o.OpCode, o.Operand) else None
let (|Shl|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 98s) then Some(o.OpCode, o.Operand) else None
let (|Shr|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 99s) then Some(o.OpCode, o.Operand) else None
let (|ShrUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 100s) then Some(o.OpCode, o.Operand) else None
let (|Sizeof|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -484s) then Some(o.OpCode, o.Operand) else None
let (|Starg|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -501s) then Some(o.OpCode, o.Operand) else None
let (|StargS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 16s) then Some(o.OpCode, o.Operand) else None
let (|Stelem|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 164s) then Some(o.OpCode, o.Operand) else None
let (|StelemI|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 155s) then Some(o.OpCode, o.Operand) else None
let (|StelemI1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 156s) then Some(o.OpCode, o.Operand) else None
let (|StelemI2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 157s) then Some(o.OpCode, o.Operand) else None
let (|StelemI4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 158s) then Some(o.OpCode, o.Operand) else None
let (|StelemI8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 159s) then Some(o.OpCode, o.Operand) else None
let (|StelemR4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 160s) then Some(o.OpCode, o.Operand) else None
let (|StelemR8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 161s) then Some(o.OpCode, o.Operand) else None
let (|StelemRef|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 162s) then Some(o.OpCode, o.Operand) else None
let (|Stfld|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 125s) then Some(o.OpCode, o.Operand) else None
let (|StindI|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 223s) then Some(o.OpCode, o.Operand) else None
let (|StindI1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 82s) then Some(o.OpCode, o.Operand) else None
let (|StindI2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 83s) then Some(o.OpCode, o.Operand) else None
let (|StindI4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 84s) then Some(o.OpCode, o.Operand) else None
let (|StindI8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 85s) then Some(o.OpCode, o.Operand) else None
let (|StindR4|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 86s) then Some(o.OpCode, o.Operand) else None
let (|StindR8|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 87s) then Some(o.OpCode, o.Operand) else None
let (|StindRef|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 81s) then Some(o.OpCode, o.Operand) else None
let (|Stloc|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -498s) then Some(o.OpCode, o.Operand) else None
let (|Stloc0|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 10s) then Some(o.OpCode, o.Operand) else None
let (|Stloc1|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 11s) then Some(o.OpCode, o.Operand) else None
let (|Stloc2|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 12s) then Some(o.OpCode, o.Operand) else None
let (|Stloc3|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 13s) then Some(o.OpCode, o.Operand) else None
let (|StlocS|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 19s) then Some(o.OpCode, o.Operand) else None
let (|Stobj|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 129s) then Some(o.OpCode, o.Operand) else None
let (|Stsfld|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 128s) then Some(o.OpCode, o.Operand) else None
let (|Sub|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 89s) then Some(o.OpCode, o.Operand) else None
let (|SubOvf|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 218s) then Some(o.OpCode, o.Operand) else None
let (|SubOvfUn|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 219s) then Some(o.OpCode, o.Operand) else None
let (|Switch|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 69s) then Some(o.OpCode, o.Operand) else None
let (|Tail|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -492s) then Some(o.OpCode, o.Operand) else None
let (|Throw|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 122s) then Some(o.OpCode, o.Operand) else None
let (|Unaligned|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -494s) then Some(o.OpCode, o.Operand) else None
let (|Unbox|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 121s) then Some(o.OpCode, o.Operand) else None
let (|UnboxAny|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 165s) then Some(o.OpCode, o.Operand) else None
let (|Volatile|_|) (o:OpCodeInfo) = if (o.OpCode.Value = -493s) then Some(o.OpCode, o.Operand) else None
let (|Xor|_|) (o:OpCodeInfo) = if (o.OpCode.Value = 97s) then Some(o.OpCode, o.Operand) else None