#!/bin/bash
gacutil -i /usr/lib/phalanger/bin/PhpNetCore.IL.dll
gacutil -i /usr/lib/phalanger/bin/PhpNetCore.dll
gacutil -i /usr/lib/phalanger/bin/PhpNetClassLibrary.dll
gacutil -i /usr/lib/phalanger/bin/PhpNetXmlDom.dll

a2enmod mod_mono

version="3.0.0.0"
machine_config="/etc/mono/4.0/machine.config"
web_config="/etc/mono/4.0/web.config"
public_key="0a8e8c4c76728c71"
public_key2="4af37afe3cde05fb"
pars="-P -L"
phalanger_folder="/usr/lib/phalanger/"

# Adding definition of phpNet section
xmlstarlet ed $pars -s "/configuration/configSections" -t elem -n "section" -v "" $machine_config
xmlstarlet ed $pars -s "/configuration/configSections/section[last()]" -t attr -n "name" -v "phpNet" $machine_config
xmlstarlet ed $pars -s "/configuration/configSections/section[last()]" -t attr -n "type" -v "PHP.Core.ConfigurationSectionHandler, PhpNetCore, Version=$version, Culture=neutral, PublicKeyToken=$public_key" $machine_config

#Registering phpNet as compiler
xmlstarlet ed $pars -s "/configuration" -t elem -n "phpNet" -v "" $machine_config
xmlstarlet ed $pars -s "/configuration/phpNet" -t elem -n "compiler" -v "" $machine_config
xmlstarlet ed $pars -s "/configuration/phpNet" -t elem -n "paths" -v "" $machine_config

#Registering Phalangers Dynamic folder
xmlstarlet ed $pars -s "/configuration/phpNet/paths" -t elem -n "set" -v "" $machine_config
xmlstarlet ed $pars -s "/configuration/phpNet/paths/set" -t attr -n "name" -v "DynamicWrappers" $machine_config
xmlstarlet ed $pars -s "/configuration/phpNet/paths/set" -t attr -n "value" -v "$phalanger_folder/dynamic" $machine_config

#Setting reference to Phalangers Libraries folder
xmlstarlet ed $pars -s "/configuration/phpNet/paths" -t elem -n "set" -v "" $machine_config
xmlstarlet ed $pars -s "/configuration/phpNet/paths/set[last()]" -t attr -n "name" -v "Libraries" $machine_config
xmlstarlet ed $pars -s "/configuration/phpNet/paths/set[last()]" -t attr -n "value" -v "$phalanger_folder/bin" $machine_config

#Registering PhpNetClassLibrary
xmlstarlet ed $pars -s "/configuration/phpNet" -t elem -n "classLibrary" -v "" $machine_config
xmlstarlet ed $pars -s "/configuration/phpNet/classLibrary" -t elem -n "add" -v "" $machine_config
xmlstarlet ed $pars -s "/configuration/phpNet/classLibrary/add" -t attr -n "assembly" -v "PhpNetClassLibrary, Version=$version, Culture=neutral, PublicKeyToken=$public_key2" $machine_config
xmlstarlet ed $pars -s "/configuration/phpNet/classLibrary/add" -t attr -n "section" -v "bcl" $machine_config

#Registering Phalanger as HttpHandler
xmlstarlet ed $pars -s "/configuration/system.web/httpHandlers" -t elem -n "add" -v "" $web_config
xmlstarlet ed $pars -s "/configuration/system.web/httpHandlers/add[last()]" -t attr -n "path" -v "*.php" $web_config
xmlstarlet ed $pars -s "/configuration/system.web/httpHandlers/add[last()]" -t attr -n "verb" -v "*" $web_config
xmlstarlet ed $pars -s "/configuration/system.web/httpHandlers/add[last()]" -t attr -n "type" -v "PHP.Core.RequestHandler, PhpNetCore, Version=$version, Culture=neutral, PublicKeyToken=$public_key" $web_config
