#!/bin/bash
gacutil -u PhpNetClasslibrary
gacutil -u PhpNetCore
gacutil -u PhpNetCore.IL
gacutil -u PhpNetXmlDom

machine_config="/etc/mono/4.0/machine.config"
web_config="/etc/mono/4.0/web.config"
pars="-PLq"

xmlstarlet ed $pars -d "/configuration/configSections[@name=phpNet]" $web_config
xmlstarlet ed $pars -d "/configuration/phpNet" $web_config
xmlstarlet ed $pars -d "/configuration/system.web/httpHandlers[@path=*.php]" $web_config
