//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHP.VisualStudio.PhalangerLanguageService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PHP.VisualStudio.PhalangerLanguageService.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Language.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQEERKICHAZ9ZMIQA1HDQHC0H9KTE2DKPZIDC0DRDPEPCMI1D2RJR1Z9I8MIQ8CQH8QZAQQ8QRZEZKAQH9A1ZHZCD0PER3E0JKRJCMPQCDEMEKKZMJCJZ3PJAKH0JAC0.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Types.
        /// </summary>
        internal static string BaseTypesNodeText {
            get {
                return ResourceManager.GetString("BaseTypesNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression property should be a string..
        /// </summary>
        internal static string CodeModelVariableExpressionNotString {
            get {
                return ResourceManager.GetString("CodeModelVariableExpressionNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Snippet.
        /// </summary>
        internal static string InsertSnippet {
            get {
                return ResourceManager.GetString("InsertSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP.
        /// </summary>
        internal static string PHP {
            get {
                return ResourceManager.GetString("PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP File (*.php)
        ///*.php.
        /// </summary>
        internal static string PHPFormatFilter {
            get {
                return ResourceManager.GetString("PHPFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surround With....
        /// </summary>
        internal static string SurroundWith {
            get {
                return ResourceManager.GetString("SurroundWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type {0}.
        /// </summary>
        internal static string UnexpectedType0 {
            get {
                return ResourceManager.GetString("UnexpectedType0", resourceCulture);
            }
        }
    }
}
