// ***
// Do not edit this file. It has been generated by the ClassDynamizer tool.
// ***
#pragma warning disable 0108
using PHP.Core.Reflection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PHP.Core;
using System.Runtime.InteropServices;
namespace PHP.Library.Soap
{
	[Serializable()]
	public partial class SoapClient
	{
        /// <summary></summary>
		protected SoapClient(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public SoapClient(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public SoapClient(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __call(ScriptContext __context, object function_name, object arguments)
		{
			
			string tmp1 = PhpVariable.AsString(function_name);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(function_name, "string", "__call");
					return null;
				}
			
			PhpArray tmp2 = arguments as PhpArray;
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(arguments, "PhpArray", "__call");
					return null;
				}
			return __call(tmp1, tmp2);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __call(object instance, PhpStack stack)
		{
			stack.CalleeName = "__call";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			stack.RemoveFrame();
			return ((SoapClient)instance).__call(stack.Context, arg1, arg2);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __doRequest(ScriptContext __context)
		{
			return __doRequest();
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __doRequest(object instance, PhpStack stack)
		{
			stack.CalleeName = "__doRequest";
			stack.RemoveFrame();
			return ((SoapClient)instance).__doRequest(stack.Context);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __getFunctions(ScriptContext __context)
		{
			return __getFunctions();
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __getFunctions(object instance, PhpStack stack)
		{
			stack.CalleeName = "__getFunctions";
			stack.RemoveFrame();
			return ((SoapClient)instance).__getFunctions(stack.Context);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __getLastRequest(ScriptContext __context)
		{
			return __getLastRequest();
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __getLastRequest(object instance, PhpStack stack)
		{
			stack.CalleeName = "__getLastRequest";
			stack.RemoveFrame();
			return ((SoapClient)instance).__getLastRequest(stack.Context);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __getLastRequestHeaders(ScriptContext __context)
		{
			return __getLastRequestHeaders();
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __getLastRequestHeaders(object instance, PhpStack stack)
		{
			stack.CalleeName = "__getLastRequestHeaders";
			stack.RemoveFrame();
			return ((SoapClient)instance).__getLastRequestHeaders(stack.Context);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __getLastResponse(ScriptContext __context)
		{
			return __getLastResponse();
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __getLastResponse(object instance, PhpStack stack)
		{
			stack.CalleeName = "__getLastResponse";
			stack.RemoveFrame();
			return ((SoapClient)instance).__getLastResponse(stack.Context);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __getLastResponseHeaders(ScriptContext __context)
		{
			return __getLastResponseHeaders();
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __getLastResponseHeaders(object instance, PhpStack stack)
		{
			stack.CalleeName = "__getLastResponseHeaders";
			stack.RemoveFrame();
			return ((SoapClient)instance).__getLastResponseHeaders(stack.Context);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __getTypes(ScriptContext __context)
		{
			return __getTypes();
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __getTypes(object instance, PhpStack stack)
		{
			stack.CalleeName = "__getTypes";
			stack.RemoveFrame();
			return ((SoapClient)instance).__getTypes(stack.Context);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __setCookie(ScriptContext __context, object name, object value)
		{
			
			string tmp1 = PhpVariable.AsString(name);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(name, "string", "__setCookie");
					return null;
				}
			
			string tmp2 = PhpVariable.AsString(value);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(value, "string", "__setCookie");
					return null;
				}
			__setCookie(tmp1, tmp2);
			return null;
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __setCookie(object instance, PhpStack stack)
		{
			stack.CalleeName = "__setCookie";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			stack.RemoveFrame();
			return ((SoapClient)instance).__setCookie(stack.Context, arg1, arg2);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __setLocation(ScriptContext __context, object new_location)
		{
			
			string tmp1 = PhpVariable.AsString(new_location);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(new_location, "string", "__setLocation");
					return null;
				}
			return __setLocation(tmp1);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __setLocation(object instance, PhpStack stack)
		{
			stack.CalleeName = "__setLocation";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((SoapClient)instance).__setLocation(stack.Context, arg1);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __setSoapHeaders(ScriptContext __context, object SoapHeaders)
		{
			
			PhpArray tmp1 = SoapHeaders as PhpArray;
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(SoapHeaders, "PhpArray", "__setSoapHeaders");
					return null;
				}
			__setSoapHeaders(tmp1);
			return null;
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __setSoapHeaders(object instance, PhpStack stack)
		{
			stack.CalleeName = "__setSoapHeaders";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((SoapClient)instance).__setSoapHeaders(stack.Context, arg1);
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __construct(ScriptContext __context, object wsdl, 		[System.Runtime.InteropServices.OptionalAttribute()]
object options)
		{
			
			string tmp1 = PhpVariable.AsString(wsdl);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(wsdl, "string", "__construct");
					return null;
				}
			
			PhpArray tmp2 = null;
			if (options != Arg.Default)

				{
					tmp2 = options as PhpArray;
					if (tmp2 == null)

						{
							PhpException.InvalidImplicitCast(options, "PhpArray", "__construct");
							return null;
						}
				}
			__construct(tmp1, tmp2);
			return null;
		}
        /// <summary></summary>
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __construct(object instance, PhpStack stack)
		{
			stack.CalleeName = "__construct";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValueOptional(2);
			stack.RemoveFrame();
			return ((SoapClient)instance).__construct(stack.Context, arg1, arg2);
		}
        /// <summary></summary>
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddMethod("__call", PhpMemberAttributes.Public, new RoutineDelegate(SoapClient.__call));
			desc.AddMethod("__doRequest", PhpMemberAttributes.Public, new RoutineDelegate(SoapClient.__doRequest));
			desc.AddMethod("__getFunctions", PhpMemberAttributes.Public, new RoutineDelegate(SoapClient.__getFunctions));
			desc.AddMethod("__getLastRequest", PhpMemberAttributes.Public, new RoutineDelegate(SoapClient.__getLastRequest));
			desc.AddMethod("__getLastRequestHeaders", PhpMemberAttributes.Public, new RoutineDelegate(SoapClient.__getLastRequestHeaders));
			desc.AddMethod("__getLastResponse", PhpMemberAttributes.Public, new RoutineDelegate(SoapClient.__getLastResponse));
			desc.AddMethod("__getLastResponseHeaders", PhpMemberAttributes.Public, new RoutineDelegate(SoapClient.__getLastResponseHeaders));
			desc.AddMethod("__getTypes", PhpMemberAttributes.Public, new RoutineDelegate(SoapClient.__getTypes));
			desc.AddMethod("__setCookie", PhpMemberAttributes.Public, new RoutineDelegate(SoapClient.__setCookie));
			desc.AddMethod("__setLocation", PhpMemberAttributes.Public, new RoutineDelegate(SoapClient.__setLocation));
			desc.AddMethod("__setSoapHeaders", PhpMemberAttributes.Public, new RoutineDelegate(SoapClient.__setSoapHeaders));
			desc.AddMethod("__construct", PhpMemberAttributes.Public, new RoutineDelegate(SoapClient.__construct));
		}
	}
}
