//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHP.Library.Soap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PHP.Library.Soap.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body must be present in a SOAP envelope.
        /// </summary>
        internal static string body_must_be_present {
            get {
                return ResourceManager.GetString("body_must_be_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t uncompress compressed response.
        /// </summary>
        internal static string cant_uncompress_response {
            get {
                return ResourceManager.GetString("cant_uncompress_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to host.
        /// </summary>
        internal static string could_not_connect {
            get {
                return ResourceManager.GetString("could_not_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoapClient::__doRequest() failed.
        /// </summary>
        internal static string dorequest_failed {
            get {
                return ResourceManager.GetString("dorequest_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoapClient::__doRequest() returned non string value.
        /// </summary>
        internal static string dorequest_returned_nonstring {
            get {
                return ResourceManager.GetString("dorequest_returned_nonstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTD are not supported by SOAP.
        /// </summary>
        internal static string dtd_not_supported {
            get {
                return ResourceManager.GetString("dtd_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encodingStyle cannot be specified on the {0}.
        /// </summary>
        internal static string encondingstyle_cannot_be_specified {
            get {
                return ResourceManager.GetString("encondingstyle_cannot_be_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching http body, No Content-Length, connection closed or chunked data.
        /// </summary>
        internal static string http_body_error {
            get {
                return ResourceManager.GetString("http_body_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching http headers.
        /// </summary>
        internal static string http_headers_error {
            get {
                return ResourceManager.GetString("http_headers_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not find &quot;location&quot; property.
        /// </summary>
        internal static string location_not_found {
            get {
                return ResourceManager.GetString("location_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find response data.
        /// </summary>
        internal static string no_response_data {
            get {
                return ResourceManager.GetString("no_response_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looks like we got no XML document.
        /// </summary>
        internal static string no_xml_document {
            get {
                return ResourceManager.GetString("no_xml_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SOAP {0} element cannot have non Namespace qualified attributes.
        /// </summary>
        internal static string non_namespace_attributes_not_allowed {
            get {
                return ResourceManager.GetString("non_namespace_attributes_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SOAP 1.2 envelope can contain only Header and Body.
        /// </summary>
        internal static string only_header_and_body_are_allowed {
            get {
                return ResourceManager.GetString("only_header_and_body_are_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t recieve an xml document.
        /// </summary>
        internal static string received_doc_not_xml {
            get {
                return ResourceManager.GetString("received_doc_not_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirection limit reached, aborting.
        /// </summary>
        internal static string redirection_limit {
            get {
                return ResourceManager.GetString("redirection_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Sending HTTP SOAP request.
        /// </summary>
        internal static string sending_failed {
            get {
                return ResourceManager.GetString("sending_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error build soap request.
        /// </summary>
        internal static string soap_request_building_error {
            get {
                return ResourceManager.GetString("soap_request_building_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL support is not available in this build.
        /// </summary>
        internal static string ssl_not_available {
            get {
                return ResourceManager.GetString("ssl_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create stream??.
        /// </summary>
        internal static string stream_create_failed {
            get {
                return ResourceManager.GetString("stream_create_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse URL.
        /// </summary>
        internal static string unable_to_parse_url {
            get {
                return ResourceManager.GetString("unable_to_parse_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown protocol. Only http and https are allowed..
        /// </summary>
        internal static string unknow_protocl {
            get {
                return ResourceManager.GetString("unknow_protocl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Content-Encoding.
        /// </summary>
        internal static string unknown_content_encoding {
            get {
                return ResourceManager.GetString("unknown_content_encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown data encoding style.
        /// </summary>
        internal static string unknown_data_encoding_style {
            get {
                return ResourceManager.GetString("unknown_data_encoding_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string unknown_error {
            get {
                return ResourceManager.GetString("unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding &quot;uri&quot; property.
        /// </summary>
        internal static string uri_not_found {
            get {
                return ResourceManager.GetString("uri_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Version.
        /// </summary>
        internal static string wrong_version {
            get {
                return ResourceManager.GetString("wrong_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing WSDL: Couldn&apos;t load from &apos;{0}&apos;.
        /// </summary>
        internal static string wsdl_could_not_load {
            get {
                return ResourceManager.GetString("wsdl_could_not_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing WSDL: Couldn&apos;t find &lt;definitions&gt; in &apos;{0}&apos;.
        /// </summary>
        internal static string wsdl_no_definitions {
            get {
                return ResourceManager.GetString("wsdl_no_definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing WSDL: Unexpected WSDL element &lt;%s&gt;.
        /// </summary>
        internal static string wsdl_unexpected_element {
            get {
                return ResourceManager.GetString("wsdl_unexpected_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looks like we got XML without \&quot;Envelope\&quot; element.
        /// </summary>
        internal static string xml_without_envelope_element {
            get {
                return ResourceManager.GetString("xml_without_envelope_element", resourceCulture);
            }
        }
    }
}
