#!/bin/bash
phalanger_version="3.0.0"
package_version=""
architecture="i386"
cp "../../Deployment/Bin/PhpNetCore.IL.dll" "Debian package/usr/lib/phalanger/bin"
cp "../../Deployment/Bin/PhpNetCore.dll" "Debian package/usr/lib/phalanger/bin"
cp "../../Deployment/Bin/PhpNetClassLibrary.dll" "Debian package/usr/lib/phalanger/bin"
cp "../../Deployment/Bin/PhpNetXmlDom.dll" "Debian package/usr/lib/phalanger/bin"
cp -r "Debian package" "/tmp/Debian package"
sudo dpkg -b "/tmp/Debian package" "../../Deployment/Bin/Package/phalanger_$phalanger_version-$architecture.deb"
rm -rf "/tmp/Debian package" 
alien -r --scripts "../../Deployment/Bin/Package/phalanger_$phalanger_version-$architecture.deb"
rpm_package="`find *.rpm`"
mv $rpm_package "../../Deployment/Bin/Package/phalanger_$phalanger_version-$architecture.rpm"
#read -p "Linux Package building finished..."
