<?php
/**
 * Auto generated by prado-cli.php on 2007-05-01 05:24:53.
 */
class Category extends TActiveRecord
{
	const TABLE='Categories';

	public $CategoryID;
	public $CategoryName;
	public $Description;
	public $Picture;

	public $Products=array();

	public static $RELATIONS=array
	(
		'Products' => array(self::HAS_MANY, 'Product'),
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>