<?php
/**
 * Auto generated by prado-cli.php on 2007-05-01 05:28:47.
 */
class Customer extends TActiveRecord
{
	const TABLE='Customers';

	public $CustomerID;
	public $CompanyName;
	public $ContactName;
	public $ContactTitle;
	public $Address;
	public $City;
	public $Region;
	public $PostalCode;
	public $Country;
	public $Phone;
	public $Fax;

	public $Orders=array();

	public static $RELATIONS = array
	(
		'Orders' => array(self::HAS_MANY, 'Order'),
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>