<?php
/**
 * Auto generated by prado-cli.php on 2007-05-01 05:29:47.
 */
class Order extends TActiveRecord
{
	const TABLE='Orders';

	public $OrderID;
	public $CustomerID;
	public $EmployeeID;
	public $OrderDate;
	public $RequiredDate;
	public $ShippedDate;
	public $ShipVia;
	public $Freight;
	public $ShipName;
	public $ShipAddress;
	public $ShipCity;
	public $ShipRegion;
	public $ShipPostalCode;
	public $ShipCountry;

	public $OrderDetails=array();
	public $Customer;
	public $Shipper;
	public $Employee;

	public static $RELATIONS = array
	(
		'OrderDetails' => array(self::HAS_MANY, 'OrderDetail'),
		'Customer' => array(self::BELONGS_TO, 'Customer'),
		'Shipper' => array(self::BELONGS_TO, 'Shipper'),
		'Employee' => array(self::BELONGS_TO, 'Employee'),
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>