<?php
/**
 * Auto generated by prado-cli.php on 2007-05-01 05:31:51.
 */
class Product extends TActiveRecord
{
	const TABLE='Products';

	public $ProductID;
	public $ProductName;
	public $SupplierID;
	public $CategoryID;
	public $QuantityPerUnit;
	public $UnitPrice;
	public $UnitsInStock;
	public $UnitsOnOrder;
	public $ReorderLevel;
	public $Discontinued;

	public $Supplier;
	public $Category;
	public $OrderDetails=array();

	public static $RELATIONS = array
	(
		'Supplier' => array(self::BELONGS_TO, 'Supplier'),
		'Category' => array(self::BELONGS_TO, 'Category'),
		'OrderDetails' => array(self::HAS_MANY, 'OrderDetail'),
	);

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>