//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHP.VisualStudio.PhalangerProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PHP.VisualStudio.PhalangerProject.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMKDEEH2CTP0PKREMKDQCQE0KCD8Q1CPQ8DPHMAQH1Q8CHP2ZZIKRAMZZQIIIKQ2ZMDEZ1IJC2JPQIRPDJAECIJRQ1EKJTMPP2JJZPEAP0JIJEJCHJZZJDZZA9RJHPD1.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon _104 {
            get {
                object obj = ResourceManager.GetObject("104", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon _105 {
            get {
                object obj = ResourceManager.GetObject("105", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Icon.
        /// </summary>
        internal static string ApplicationIcon {
            get {
                return ResourceManager.GetString("ApplicationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the .ico file to use as your application icon..
        /// </summary>
        internal static string ApplicationIconDescription {
            get {
                return ResourceManager.GetString("ApplicationIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name.
        /// </summary>
        internal static string AssemblyName {
            get {
                return ResourceManager.GetString("AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the output file that will hold assembly metadata..
        /// </summary>
        internal static string AssemblyNameDescription {
            get {
                return ResourceManager.GetString("AssemblyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation Mode.
        /// </summary>
        internal static string CompilationMode {
            get {
                return ResourceManager.GetString("CompilationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode of the compilation; choose Standard for backward compatibility with PHP.
        /// </summary>
        internal static string CompilationModeDescription {
            get {
                return ResourceManager.GetString("CompilationModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Namespace.
        /// </summary>
        internal static string DefaultNamespace {
            get {
                return ResourceManager.GetString("DefaultNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the default namespace for added items, such as classes, that are added via the Add New Item Dialog Box..
        /// </summary>
        internal static string DefaultNamespaceDescription {
            get {
                return ResourceManager.GetString("DefaultNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled Warnings.
        /// </summary>
        internal static string DisabledWarnings {
            get {
                return ResourceManager.GetString("DisabledWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of comma separated warning numbers that shall not be reported by the compiler..
        /// </summary>
        internal static string DisabledWarningsDescription {
            get {
                return ResourceManager.GetString("DisabledWarningsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralCaption {
            get {
                return ResourceManager.GetString("GeneralCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Features.
        /// </summary>
        internal static string LanguageFeatures {
            get {
                return ResourceManager.GetString("LanguageFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of comma separated language features that should be enabled. The list can contain a language name
        ///(one of Php4, Php5, Php6 and PhpClr -- the higher version includes the features of the lower one),
        ///tags options (ShortOpenTags, AspTags -- both enabled by default), and/or explicit features (V5Keywords,
        ///V6Keywords, UnicodeSemantics, ClrSemantics, TypeKeywords, Linq)..
        /// </summary>
        internal static string LanguageFeaturesDescription {
            get {
                return ResourceManager.GetString("LanguageFeaturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        internal static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the project&apos;s primary output file..
        /// </summary>
        internal static string OutputFileDescription {
            get {
                return ResourceManager.GetString("OutputFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Type.
        /// </summary>
        internal static string OutputType {
            get {
                return ResourceManager.GetString("OutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of application to build..
        /// </summary>
        internal static string OutputTypeDescription {
            get {
                return ResourceManager.GetString("OutputTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project File.
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the file containing build, configuration, and other information about the project..
        /// </summary>
        internal static string ProjectFileDescription {
            get {
                return ResourceManager.GetString("ProjectFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phalanger Project File (*.phpproj){0}*.phpproj{1}.
        /// </summary>
        internal static string ProjectFileExtensionFilter {
            get {
                return ResourceManager.GetString("ProjectFileExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Folder.
        /// </summary>
        internal static string ProjectFolder {
            get {
                return ResourceManager.GetString("ProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absolute location of the project..
        /// </summary>
        internal static string ProjectFolderDescription {
            get {
                return ResourceManager.GetString("ProjectFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup File/Class.
        /// </summary>
        internal static string StartupObject {
            get {
                return ResourceManager.GetString("StartupObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For standard mode executable applications, the name of the script that you want to start
        ///when you launch your application (mandatory if the project comprises of multiple scripts).
        ///For pure executable applications, a name of the class that contains the static parameterless
        ///Main method you want to execute when you launch the application (optional, if not specified
        ///there must be a single parameterless Main function or static method within the project)..
        /// </summary>
        internal static string StartupObjectDescription {
            get {
                return ResourceManager.GetString("StartupObjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Platform.
        /// </summary>
        internal static string TargetPlatform {
            get {
                return ResourceManager.GetString("TargetPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the Common Language Runtime to use for output assembly.
        /// </summary>
        internal static string TargetPlatformDescription {
            get {
                return ResourceManager.GetString("TargetPlatformDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Platform Location.
        /// </summary>
        internal static string TargetPlatformLocation {
            get {
                return ResourceManager.GetString("TargetPlatformLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the target platform.
        /// </summary>
        internal static string TargetPlatformLocationDescription {
            get {
                return ResourceManager.GetString("TargetPlatformLocationDescription", resourceCulture);
            }
        }
    }
}
