// ***
// Do not edit this file. It has been generated by the ClassDynamizer tool.
// ***
#pragma warning disable 0108
using PHP.Core.Reflection;
using System;
using System.Xml;
using System.Xml.Schema;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using PHP.Core;
namespace PHP.Library.Xml
{
	[Serializable()]
	public partial class DOMAttr
	{
		protected DOMAttr(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMAttr(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMAttr(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_nodeName(object instance)
		{
			return ((DOMAttr)instance).nodeName;
		}
		private static object __get_nodeValue(object instance)
		{
			return ((DOMAttr)instance).nodeValue;
		}
		private static void __set_nodeValue(object instance, object value)
		{
			((DOMAttr)instance).nodeValue = value;
		}
		private static object __get_namespaceURI(object instance)
		{
			return ((DOMAttr)instance).namespaceURI;
		}
		private static object __get_nodeType(object instance)
		{
			return ((DOMAttr)instance).nodeType;
		}
		private static object __get_name(object instance)
		{
			return ((DOMAttr)instance).name;
		}
		private static object __get_value(object instance)
		{
			return ((DOMAttr)instance).value;
		}
		private static void __set_value(object instance, object value)
		{
			((DOMAttr)instance).value = value;
		}
		private static object __get_ownerElement(object instance)
		{
			return ((DOMAttr)instance).ownerElement;
		}
		private static object __get_schemaTypeInfo(object instance)
		{
			return ((DOMAttr)instance).schemaTypeInfo;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __construct(ScriptContext __context, object name, 		[System.Runtime.InteropServices.OptionalAttribute()]
object value)
		{
			
			string tmp1 = PhpVariable.AsString(name);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(name, "string", "__construct");
					return null;
				}
			
			string tmp2 = null;
			if (value != Arg.Default)

				{
					tmp2 = PhpVariable.AsString(value);
					if (tmp2 == null)

						{
							PhpException.InvalidImplicitCast(value, "string", "__construct");
							return null;
						}
				}
			__construct(tmp1, tmp2);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __construct(object instance, PhpStack stack)
		{
			stack.CalleeName = "__construct";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValueOptional(2);
			stack.RemoveFrame();
			return ((DOMAttr)instance).__construct(stack.Context, arg1, arg2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object isId(ScriptContext __context)
		{
			return isId();
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object isId(object instance, PhpStack stack)
		{
			stack.CalleeName = "isId";
			stack.RemoveFrame();
			return ((DOMAttr)instance).isId(stack.Context);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("nodeName", PhpMemberAttributes.Public, new GetterDelegate(DOMAttr.__get_nodeName), null);
			desc.AddProperty("nodeValue", PhpMemberAttributes.Public, new GetterDelegate(DOMAttr.__get_nodeValue), new SetterDelegate(DOMAttr.__set_nodeValue));
			desc.AddProperty("namespaceURI", PhpMemberAttributes.Public, new GetterDelegate(DOMAttr.__get_namespaceURI), null);
			desc.AddProperty("nodeType", PhpMemberAttributes.Public, new GetterDelegate(DOMAttr.__get_nodeType), null);
			desc.AddProperty("name", PhpMemberAttributes.Public, new GetterDelegate(DOMAttr.__get_name), null);
			desc.AddProperty("value", PhpMemberAttributes.Public, new GetterDelegate(DOMAttr.__get_value), new SetterDelegate(DOMAttr.__set_value));
			desc.AddProperty("ownerElement", PhpMemberAttributes.Public, new GetterDelegate(DOMAttr.__get_ownerElement), null);
			desc.AddProperty("schemaTypeInfo", PhpMemberAttributes.Public, new GetterDelegate(DOMAttr.__get_schemaTypeInfo), null);
			desc.AddMethod("__construct", PhpMemberAttributes.Public, new RoutineDelegate(DOMAttr.__construct));
			desc.AddMethod("isId", PhpMemberAttributes.Public, new RoutineDelegate(DOMAttr.isId));
		}
	}
}
