// ***
// Do not edit this file. It has been generated by the ClassDynamizer tool.
// ***
#pragma warning disable 0108
using PHP.Core.Reflection;
using System;
using System.Xml;
using System.Xml.Schema;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using PHP.Core;
namespace PHP.Library.Xml
{
	[Serializable()]
	public partial class DOMCharacterData
	{
		protected DOMCharacterData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMCharacterData(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMCharacterData(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_data(object instance)
		{
			return ((DOMCharacterData)instance).data;
		}
		private static void __set_data(object instance, object value)
		{
			((DOMCharacterData)instance).data = value;
		}
		private static object __get_length(object instance)
		{
			return ((DOMCharacterData)instance).length;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object substringData(ScriptContext __context, object offset, object count)
		{
			if (!(offset is int))

				{
					PhpException.InvalidImplicitCast(offset, "int", "substringData");
					return null;
				}
			if (!(count is int))

				{
					PhpException.InvalidImplicitCast(count, "int", "substringData");
					return null;
				}
			return substringData((int)offset, (int)count);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object substringData(object instance, PhpStack stack)
		{
			stack.CalleeName = "substringData";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			stack.RemoveFrame();
			return ((DOMCharacterData)instance).substringData(stack.Context, arg1, arg2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object appendData(ScriptContext __context, object arg)
		{
			
			string tmp1 = PhpVariable.AsString(arg);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(arg, "string", "appendData");
					return null;
				}
			return appendData(tmp1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object appendData(object instance, PhpStack stack)
		{
			stack.CalleeName = "appendData";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMCharacterData)instance).appendData(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object insertData(ScriptContext __context, object offset, object arg)
		{
			if (!(offset is int))

				{
					PhpException.InvalidImplicitCast(offset, "int", "insertData");
					return null;
				}
			
			string tmp2 = PhpVariable.AsString(arg);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(arg, "string", "insertData");
					return null;
				}
			return insertData((int)offset, tmp2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object insertData(object instance, PhpStack stack)
		{
			stack.CalleeName = "insertData";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			stack.RemoveFrame();
			return ((DOMCharacterData)instance).insertData(stack.Context, arg1, arg2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object deleteData(ScriptContext __context, object offset, object count)
		{
			if (!(offset is int))

				{
					PhpException.InvalidImplicitCast(offset, "int", "deleteData");
					return null;
				}
			if (!(count is int))

				{
					PhpException.InvalidImplicitCast(count, "int", "deleteData");
					return null;
				}
			return deleteData((int)offset, (int)count);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object deleteData(object instance, PhpStack stack)
		{
			stack.CalleeName = "deleteData";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			stack.RemoveFrame();
			return ((DOMCharacterData)instance).deleteData(stack.Context, arg1, arg2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object replaceData(ScriptContext __context, object offset, object count, object arg)
		{
			if (!(offset is int))

				{
					PhpException.InvalidImplicitCast(offset, "int", "replaceData");
					return null;
				}
			if (!(count is int))

				{
					PhpException.InvalidImplicitCast(count, "int", "replaceData");
					return null;
				}
			
			string tmp3 = PhpVariable.AsString(arg);
			if (tmp3 == null)

				{
					PhpException.InvalidImplicitCast(arg, "string", "replaceData");
					return null;
				}
			return replaceData((int)offset, (int)count, tmp3);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object replaceData(object instance, PhpStack stack)
		{
			stack.CalleeName = "replaceData";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			
			object arg3 = stack.PeekValue(3);
			stack.RemoveFrame();
			return ((DOMCharacterData)instance).replaceData(stack.Context, arg1, arg2, arg3);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("data", PhpMemberAttributes.Public, new GetterDelegate(DOMCharacterData.__get_data), new SetterDelegate(DOMCharacterData.__set_data));
			desc.AddProperty("length", PhpMemberAttributes.Public, new GetterDelegate(DOMCharacterData.__get_length), null);
			desc.AddMethod("substringData", PhpMemberAttributes.Public, new RoutineDelegate(DOMCharacterData.substringData));
			desc.AddMethod("appendData", PhpMemberAttributes.Public, new RoutineDelegate(DOMCharacterData.appendData));
			desc.AddMethod("insertData", PhpMemberAttributes.Public, new RoutineDelegate(DOMCharacterData.insertData));
			desc.AddMethod("deleteData", PhpMemberAttributes.Public, new RoutineDelegate(DOMCharacterData.deleteData));
			desc.AddMethod("replaceData", PhpMemberAttributes.Public, new RoutineDelegate(DOMCharacterData.replaceData));
		}
	}
	[Serializable()]
	public partial class DOMText
	{
		protected DOMText(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMText(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMText(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_nodeName(object instance)
		{
			return ((DOMText)instance).nodeName;
		}
		private static object __get_nodeValue(object instance)
		{
			return ((DOMText)instance).nodeValue;
		}
		private static void __set_nodeValue(object instance, object value)
		{
			((DOMText)instance).nodeValue = value;
		}
		private static object __get_namespaceURI(object instance)
		{
			return ((DOMText)instance).namespaceURI;
		}
		private static object __get_nodeType(object instance)
		{
			return ((DOMText)instance).nodeType;
		}
		private static object __get_wholeText(object instance)
		{
			return ((DOMText)instance).wholeText;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual object __construct(ScriptContext __context, 		[System.Runtime.InteropServices.OptionalAttribute()]
object value)
		{
			
			string tmp1 = null;
			if (value != Arg.Default)

				{
					tmp1 = PhpVariable.AsString(value);
					if (tmp1 == null)

						{
							PhpException.InvalidImplicitCast(value, "string", "__construct");
							return null;
						}
				}
			__construct(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __construct(object instance, PhpStack stack)
		{
			stack.CalleeName = "__construct";
			
			object arg1 = stack.PeekValueOptional(1);
			stack.RemoveFrame();
			return ((DOMText)instance).__construct(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object splitText(ScriptContext __context, object offset)
		{
			if (!(offset is int))

				{
					PhpException.InvalidImplicitCast(offset, "int", "splitText");
					return null;
				}
			return splitText((int)offset);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object splitText(object instance, PhpStack stack)
		{
			stack.CalleeName = "splitText";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMText)instance).splitText(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object isWhitespaceInElementContent(ScriptContext __context)
		{
			return isWhitespaceInElementContent();
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object isWhitespaceInElementContent(object instance, PhpStack stack)
		{
			stack.CalleeName = "isWhitespaceInElementContent";
			stack.RemoveFrame();
			return ((DOMText)instance).isWhitespaceInElementContent(stack.Context);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object isElementContentWhitespace(ScriptContext __context)
		{
			return isElementContentWhitespace();
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object isElementContentWhitespace(object instance, PhpStack stack)
		{
			stack.CalleeName = "isElementContentWhitespace";
			stack.RemoveFrame();
			return ((DOMText)instance).isElementContentWhitespace(stack.Context);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object replaceWholeText(ScriptContext __context, object context)
		{
			
			string tmp1 = PhpVariable.AsString(context);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(context, "string", "replaceWholeText");
					return null;
				}
			replaceWholeText(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object replaceWholeText(object instance, PhpStack stack)
		{
			stack.CalleeName = "replaceWholeText";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMText)instance).replaceWholeText(stack.Context, arg1);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("nodeName", PhpMemberAttributes.Public, new GetterDelegate(DOMText.__get_nodeName), null);
			desc.AddProperty("nodeValue", PhpMemberAttributes.Public, new GetterDelegate(DOMText.__get_nodeValue), new SetterDelegate(DOMText.__set_nodeValue));
			desc.AddProperty("namespaceURI", PhpMemberAttributes.Public, new GetterDelegate(DOMText.__get_namespaceURI), null);
			desc.AddProperty("nodeType", PhpMemberAttributes.Public, new GetterDelegate(DOMText.__get_nodeType), null);
			desc.AddProperty("wholeText", PhpMemberAttributes.Public, new GetterDelegate(DOMText.__get_wholeText), null);
			desc.AddMethod("__construct", PhpMemberAttributes.Public, new RoutineDelegate(DOMText.__construct));
			desc.AddMethod("splitText", PhpMemberAttributes.Public, new RoutineDelegate(DOMText.splitText));
			desc.AddMethod("isWhitespaceInElementContent", PhpMemberAttributes.Public, new RoutineDelegate(DOMText.isWhitespaceInElementContent));
			desc.AddMethod("isElementContentWhitespace", PhpMemberAttributes.Public, new RoutineDelegate(DOMText.isElementContentWhitespace));
			desc.AddMethod("replaceWholeText", PhpMemberAttributes.Public, new RoutineDelegate(DOMText.replaceWholeText));
		}
	}
	[Serializable()]
	public partial class DOMCdataSection
	{
		protected DOMCdataSection(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMCdataSection(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMCdataSection(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_nodeName(object instance)
		{
			return ((DOMCdataSection)instance).nodeName;
		}
		private static object __get_nodeType(object instance)
		{
			return ((DOMCdataSection)instance).nodeType;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public override object __construct(ScriptContext __context, object value)
		{
			
			string tmp1 = PhpVariable.AsString(value);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(value, "string", "__construct");
					return null;
				}
			__construct(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __construct(object instance, PhpStack stack)
		{
			stack.CalleeName = "__construct";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMCdataSection)instance).__construct(stack.Context, arg1);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("nodeName", PhpMemberAttributes.Public, new GetterDelegate(DOMCdataSection.__get_nodeName), null);
			desc.AddProperty("nodeType", PhpMemberAttributes.Public, new GetterDelegate(DOMCdataSection.__get_nodeType), null);
			desc.AddMethod("__construct", PhpMemberAttributes.Public, new RoutineDelegate(DOMCdataSection.__construct));
		}
	}
	[Serializable()]
	public partial class DOMComment
	{
		protected DOMComment(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMComment(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMComment(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_nodeName(object instance)
		{
			return ((DOMComment)instance).nodeName;
		}
		private static object __get_nodeValue(object instance)
		{
			return ((DOMComment)instance).nodeValue;
		}
		private static void __set_nodeValue(object instance, object value)
		{
			((DOMComment)instance).nodeValue = value;
		}
		private static object __get_namespaceURI(object instance)
		{
			return ((DOMComment)instance).namespaceURI;
		}
		private static object __get_nodeType(object instance)
		{
			return ((DOMComment)instance).nodeType;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __construct(ScriptContext __context, 		[System.Runtime.InteropServices.OptionalAttribute()]
object value)
		{
			
			string tmp1 = null;
			if (value != Arg.Default)

				{
					tmp1 = PhpVariable.AsString(value);
					if (tmp1 == null)

						{
							PhpException.InvalidImplicitCast(value, "string", "__construct");
							return null;
						}
				}
			__construct(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __construct(object instance, PhpStack stack)
		{
			stack.CalleeName = "__construct";
			
			object arg1 = stack.PeekValueOptional(1);
			stack.RemoveFrame();
			return ((DOMComment)instance).__construct(stack.Context, arg1);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("nodeName", PhpMemberAttributes.Public, new GetterDelegate(DOMComment.__get_nodeName), null);
			desc.AddProperty("nodeValue", PhpMemberAttributes.Public, new GetterDelegate(DOMComment.__get_nodeValue), new SetterDelegate(DOMComment.__set_nodeValue));
			desc.AddProperty("namespaceURI", PhpMemberAttributes.Public, new GetterDelegate(DOMComment.__get_namespaceURI), null);
			desc.AddProperty("nodeType", PhpMemberAttributes.Public, new GetterDelegate(DOMComment.__get_nodeType), null);
			desc.AddMethod("__construct", PhpMemberAttributes.Public, new RoutineDelegate(DOMComment.__construct));
		}
	}
}
