// ***
// Do not edit this file. It has been generated by the ClassDynamizer tool.
// ***
#pragma warning disable 0108
using PHP.Core.Reflection;
using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using PHP.Core;
namespace PHP.Library.Xml
{
	[Serializable()]
	public partial class DOMNodeList : PhpObject
	{
		protected DOMNodeList(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMNodeList(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
			list = new List<IXmlDomNode>();
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMNodeList(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_length(object instance)
		{
			return ((DOMNodeList)instance).length;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object item(ScriptContext __context, object index)
		{
			if (!(index is int))

				{
					PhpException.InvalidImplicitCast(index, "int", "item");
					return null;
				}
			return item((int)index);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object item(object instance, PhpStack stack)
		{
			stack.CalleeName = "item";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMNodeList)instance).item(stack.Context, arg1);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("length", PhpMemberAttributes.Public, new GetterDelegate(DOMNodeList.__get_length), null);
			desc.AddMethod("item", PhpMemberAttributes.Public, new RoutineDelegate(DOMNodeList.item));
		}
	}
	[Serializable()]
	public partial class DOMNamedNodeMap : PhpObject
	{
		protected DOMNamedNodeMap(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMNamedNodeMap(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
			map = new OrderedHashtable<MapKey>();
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMNamedNodeMap(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_length(object instance)
		{
			return ((DOMNamedNodeMap)instance).length;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object getNamedItem(ScriptContext __context, object name)
		{
			
			string tmp1 = PhpVariable.AsString(name);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(name, "string", "getNamedItem");
					return null;
				}
			return getNamedItem(tmp1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object getNamedItem(object instance, PhpStack stack)
		{
			stack.CalleeName = "getNamedItem";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMNamedNodeMap)instance).getNamedItem(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object setNamedItem(ScriptContext __context, object item)
		{
			
			DOMNode tmp1 = item as DOMNode;
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(item, "DOMNode", "setNamedItem");
					return null;
				}
			setNamedItem(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object setNamedItem(object instance, PhpStack stack)
		{
			stack.CalleeName = "setNamedItem";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMNamedNodeMap)instance).setNamedItem(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object removeNamedItem(ScriptContext __context, object name)
		{
			
			string tmp1 = PhpVariable.AsString(name);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(name, "string", "removeNamedItem");
					return null;
				}
			removeNamedItem(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object removeNamedItem(object instance, PhpStack stack)
		{
			stack.CalleeName = "removeNamedItem";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMNamedNodeMap)instance).removeNamedItem(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object item(ScriptContext __context, object index)
		{
			if (!(index is int))

				{
					PhpException.InvalidImplicitCast(index, "int", "item");
					return null;
				}
			return item((int)index);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object item(object instance, PhpStack stack)
		{
			stack.CalleeName = "item";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMNamedNodeMap)instance).item(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object getNamedItemNS(ScriptContext __context, object namespaceUri, object localName)
		{
			
			string tmp1 = PhpVariable.AsString(namespaceUri);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(namespaceUri, "string", "getNamedItemNS");
					return null;
				}
			
			string tmp2 = PhpVariable.AsString(localName);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(localName, "string", "getNamedItemNS");
					return null;
				}
			return getNamedItemNS(tmp1, tmp2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object getNamedItemNS(object instance, PhpStack stack)
		{
			stack.CalleeName = "getNamedItemNS";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			stack.RemoveFrame();
			return ((DOMNamedNodeMap)instance).getNamedItemNS(stack.Context, arg1, arg2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object setNamedItemNS(ScriptContext __context, object item)
		{
			
			DOMNode tmp1 = item as DOMNode;
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(item, "DOMNode", "setNamedItemNS");
					return null;
				}
			setNamedItemNS(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object setNamedItemNS(object instance, PhpStack stack)
		{
			stack.CalleeName = "setNamedItemNS";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMNamedNodeMap)instance).setNamedItemNS(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object removeNamedItemNS(ScriptContext __context, object namespaceUri, object localName)
		{
			
			string tmp1 = PhpVariable.AsString(namespaceUri);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(namespaceUri, "string", "removeNamedItemNS");
					return null;
				}
			
			string tmp2 = PhpVariable.AsString(localName);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(localName, "string", "removeNamedItemNS");
					return null;
				}
			removeNamedItemNS(tmp1, tmp2);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object removeNamedItemNS(object instance, PhpStack stack)
		{
			stack.CalleeName = "removeNamedItemNS";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			stack.RemoveFrame();
			return ((DOMNamedNodeMap)instance).removeNamedItemNS(stack.Context, arg1, arg2);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("length", PhpMemberAttributes.Public, new GetterDelegate(DOMNamedNodeMap.__get_length), null);
			desc.AddMethod("getNamedItem", PhpMemberAttributes.Public, new RoutineDelegate(DOMNamedNodeMap.getNamedItem));
			desc.AddMethod("setNamedItem", PhpMemberAttributes.Public, new RoutineDelegate(DOMNamedNodeMap.setNamedItem));
			desc.AddMethod("removeNamedItem", PhpMemberAttributes.Public, new RoutineDelegate(DOMNamedNodeMap.removeNamedItem));
			desc.AddMethod("item", PhpMemberAttributes.Public, new RoutineDelegate(DOMNamedNodeMap.item));
			desc.AddMethod("getNamedItemNS", PhpMemberAttributes.Public, new RoutineDelegate(DOMNamedNodeMap.getNamedItemNS));
			desc.AddMethod("setNamedItemNS", PhpMemberAttributes.Public, new RoutineDelegate(DOMNamedNodeMap.setNamedItemNS));
			desc.AddMethod("removeNamedItemNS", PhpMemberAttributes.Public, new RoutineDelegate(DOMNamedNodeMap.removeNamedItemNS));
		}
	}
	[Serializable()]
	public partial class DOMStringList : PhpObject
	{
		protected DOMStringList(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMStringList(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMStringList(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_length(object instance)
		{
			return ((DOMStringList)instance).length;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object item(ScriptContext __context, object index)
		{
			if (!(index is int))

				{
					PhpException.InvalidImplicitCast(index, "int", "item");
					return null;
				}
			item((int)index);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object item(object instance, PhpStack stack)
		{
			stack.CalleeName = "item";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMStringList)instance).item(stack.Context, arg1);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("length", PhpMemberAttributes.Public, new GetterDelegate(DOMStringList.__get_length), null);
			desc.AddMethod("item", PhpMemberAttributes.Public, new RoutineDelegate(DOMStringList.item));
		}
	}
	[Serializable()]
	public partial class DOMNameList : PhpObject
	{
		protected DOMNameList(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMNameList(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMNameList(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_length(object instance)
		{
			return ((DOMNameList)instance).length;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object getName(ScriptContext __context, object index)
		{
			if (!(index is int))

				{
					PhpException.InvalidImplicitCast(index, "int", "getName");
					return null;
				}
			getName((int)index);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object getName(object instance, PhpStack stack)
		{
			stack.CalleeName = "getName";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMNameList)instance).getName(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object getNamespaceURI(ScriptContext __context, object index)
		{
			if (!(index is int))

				{
					PhpException.InvalidImplicitCast(index, "int", "getNamespaceURI");
					return null;
				}
			getNamespaceURI((int)index);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object getNamespaceURI(object instance, PhpStack stack)
		{
			stack.CalleeName = "getNamespaceURI";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMNameList)instance).getNamespaceURI(stack.Context, arg1);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("length", PhpMemberAttributes.Public, new GetterDelegate(DOMNameList.__get_length), null);
			desc.AddMethod("getName", PhpMemberAttributes.Public, new RoutineDelegate(DOMNameList.getName));
			desc.AddMethod("getNamespaceURI", PhpMemberAttributes.Public, new RoutineDelegate(DOMNameList.getNamespaceURI));
		}
	}
	[Serializable()]
	public partial class DOMImplementationList : PhpObject
	{
		protected DOMImplementationList(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMImplementationList(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMImplementationList(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_length(object instance)
		{
			return ((DOMImplementationList)instance).length;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object item(ScriptContext __context, object index)
		{
			if (!(index is int))

				{
					PhpException.InvalidImplicitCast(index, "int", "item");
					return null;
				}
			item((int)index);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object item(object instance, PhpStack stack)
		{
			stack.CalleeName = "item";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMImplementationList)instance).item(stack.Context, arg1);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("length", PhpMemberAttributes.Public, new GetterDelegate(DOMImplementationList.__get_length), null);
			desc.AddMethod("item", PhpMemberAttributes.Public, new RoutineDelegate(DOMImplementationList.item));
		}
	}
	[Serializable()]
	public partial class DOMStringExtend : PhpObject
	{
		protected DOMStringExtend(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMStringExtend(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMStringExtend(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object findOffset16(ScriptContext __context, object offset16)
		{
			if (!(offset16 is int))

				{
					PhpException.InvalidImplicitCast(offset16, "int", "findOffset16");
					return null;
				}
			findOffset16((int)offset16);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object findOffset16(object instance, PhpStack stack)
		{
			stack.CalleeName = "findOffset16";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMStringExtend)instance).findOffset16(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object findOffset32(ScriptContext __context, object offset32)
		{
			if (!(offset32 is int))

				{
					PhpException.InvalidImplicitCast(offset32, "int", "findOffset32");
					return null;
				}
			findOffset32((int)offset32);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object findOffset32(object instance, PhpStack stack)
		{
			stack.CalleeName = "findOffset32";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMStringExtend)instance).findOffset32(stack.Context, arg1);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddMethod("findOffset16", PhpMemberAttributes.Public, new RoutineDelegate(DOMStringExtend.findOffset16));
			desc.AddMethod("findOffset32", PhpMemberAttributes.Public, new RoutineDelegate(DOMStringExtend.findOffset32));
		}
	}
}
