// ***
// Do not edit this file. It has been generated by the ClassDynamizer tool.
// ***
#pragma warning disable 0108
using PHP.Core.Reflection;
using System;
using System.IO;
using System.Xml;
using System.Xml.XPath;
using System.Xml.Schema;
using System.Text;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using PHP.Core;
namespace PHP.Library.Xml
{
	[Serializable()]
	public partial class DOMDocument
	{
		protected DOMDocument(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMDocument(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
			this.XmlDocument = new XmlDocument();
			this.XmlDocument.PreserveWhitespace = true;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMDocument(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_nodeName(object instance)
		{
			return ((DOMDocument)instance).nodeName;
		}
		private static object __get_nodeValue(object instance)
		{
			return ((DOMDocument)instance).nodeValue;
		}
		private static void __set_nodeValue(object instance, object value)
		{
			((DOMDocument)instance).nodeValue = value;
		}
		private static object __get_nodeType(object instance)
		{
			return ((DOMDocument)instance).nodeType;
		}
		private static object __get_doctype(object instance)
		{
			return ((DOMDocument)instance).doctype;
		}
		private static object __get_implementation(object instance)
		{
			return ((DOMDocument)instance).implementation;
		}
		private static object __get_documentElement(object instance)
		{
			return ((DOMDocument)instance).documentElement;
		}
		private static object __get_actualEncoding(object instance)
		{
			return ((DOMDocument)instance).actualEncoding;
		}
		private static object __get_xmlEncoding(object instance)
		{
			return ((DOMDocument)instance).xmlEncoding;
		}
		private static object __get_encoding(object instance)
		{
			return ((DOMDocument)instance).encoding;
		}
		private static void __set_encoding(object instance, object value)
		{
			((DOMDocument)instance).encoding = value;
		}
		private static object __get_xmlStandalone(object instance)
		{
			return ((DOMDocument)instance).xmlStandalone;
		}
		private static void __set_xmlStandalone(object instance, object value)
		{
			((DOMDocument)instance).xmlStandalone = value;
		}
		private static object __get_standalone(object instance)
		{
			return ((DOMDocument)instance).standalone;
		}
		private static void __set_standalone(object instance, object value)
		{
			((DOMDocument)instance).standalone = value;
		}
		private static object __get_xmlVersion(object instance)
		{
			return ((DOMDocument)instance).xmlVersion;
		}
		private static void __set_xmlVersion(object instance, object value)
		{
			((DOMDocument)instance).xmlVersion = value;
		}
		private static object __get_version(object instance)
		{
			return ((DOMDocument)instance).version;
		}
		private static void __set_version(object instance, object value)
		{
			((DOMDocument)instance).version = value;
		}
		private static object __get_strictErrorChecking(object instance)
		{
			return ((DOMDocument)instance).strictErrorChecking;
		}
		private static void __set_strictErrorChecking(object instance, object value)
		{
			((DOMDocument)instance).strictErrorChecking = value;
		}
		private static object __get_documentURI(object instance)
		{
			return ((DOMDocument)instance).documentURI;
		}
		private static void __set_documentURI(object instance, object value)
		{
			((DOMDocument)instance).documentURI = value;
		}
		private static object __get_config(object instance)
		{
			return ((DOMDocument)instance).config;
		}
		private static object __get_formatOutput(object instance)
		{
			return ((DOMDocument)instance).formatOutput;
		}
		private static void __set_formatOutput(object instance, object value)
		{
			((DOMDocument)instance).formatOutput = value;
		}
		private static object __get_validateOnParse(object instance)
		{
			return ((DOMDocument)instance).validateOnParse;
		}
		private static void __set_validateOnParse(object instance, object value)
		{
			((DOMDocument)instance).validateOnParse = value;
		}
		private static object __get_resolveExternals(object instance)
		{
			return ((DOMDocument)instance).resolveExternals;
		}
		private static void __set_resolveExternals(object instance, object value)
		{
			((DOMDocument)instance).resolveExternals = value;
		}
		private static object __get_preserveWhiteSpace(object instance)
		{
			return ((DOMDocument)instance).preserveWhiteSpace;
		}
		private static void __set_preserveWhiteSpace(object instance, object value)
		{
			((DOMDocument)instance).preserveWhiteSpace = value;
		}
		private static object __get_recover(object instance)
		{
			return ((DOMDocument)instance).recover;
		}
		private static void __set_recover(object instance, object value)
		{
			((DOMDocument)instance).recover = value;
		}
		private static object __get_substituteEntities(object instance)
		{
			return ((DOMDocument)instance).substituteEntities;
		}
		private static void __set_substituteEntities(object instance, object value)
		{
			((DOMDocument)instance).substituteEntities = value;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __construct(ScriptContext __context, 		[System.Runtime.InteropServices.OptionalAttribute()]
object version, 		[System.Runtime.InteropServices.OptionalAttribute()]
object encoding)
		{
			
			string tmp1 = null;
			if (version != Arg.Default)

				{
					tmp1 = PhpVariable.AsString(version);
					if (tmp1 == null)

						{
							PhpException.InvalidImplicitCast(version, "string", "__construct");
							return null;
						}
				}
			
			string tmp2 = null;
			if (encoding != Arg.Default)

				{
					tmp2 = PhpVariable.AsString(encoding);
					if (tmp2 == null)

						{
							PhpException.InvalidImplicitCast(encoding, "string", "__construct");
							return null;
						}
				}
			__construct(tmp1, tmp2);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __construct(object instance, PhpStack stack)
		{
			stack.CalleeName = "__construct";
			
			object arg1 = stack.PeekValueOptional(1);
			
			object arg2 = stack.PeekValueOptional(2);
			stack.RemoveFrame();
			return ((DOMDocument)instance).__construct(stack.Context, arg1, arg2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object createElement(ScriptContext __context, object tagName, 		[System.Runtime.InteropServices.OptionalAttribute()]
object value)
		{
			
			string tmp1 = PhpVariable.AsString(tagName);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(tagName, "string", "createElement");
					return null;
				}
			
			string tmp2 = null;
			if (value != Arg.Default)

				{
					tmp2 = PhpVariable.AsString(value);
					if (tmp2 == null)

						{
							PhpException.InvalidImplicitCast(value, "string", "createElement");
							return null;
						}
				}
			return createElement(tmp1, tmp2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object createElement(object instance, PhpStack stack)
		{
			stack.CalleeName = "createElement";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValueOptional(2);
			stack.RemoveFrame();
			return ((DOMDocument)instance).createElement(stack.Context, arg1, arg2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object createDocumentFragment(ScriptContext __context)
		{
			return createDocumentFragment();
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object createDocumentFragment(object instance, PhpStack stack)
		{
			stack.CalleeName = "createDocumentFragment";
			stack.RemoveFrame();
			return ((DOMDocument)instance).createDocumentFragment(stack.Context);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object createTextNode(ScriptContext __context, object data)
		{
			
			string tmp1 = PhpVariable.AsString(data);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(data, "string", "createTextNode");
					return null;
				}
			return createTextNode(tmp1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object createTextNode(object instance, PhpStack stack)
		{
			stack.CalleeName = "createTextNode";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).createTextNode(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object createComment(ScriptContext __context, object data)
		{
			
			string tmp1 = PhpVariable.AsString(data);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(data, "string", "createComment");
					return null;
				}
			return createComment(tmp1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object createComment(object instance, PhpStack stack)
		{
			stack.CalleeName = "createComment";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).createComment(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object createCDATASection(ScriptContext __context, object data)
		{
			
			string tmp1 = PhpVariable.AsString(data);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(data, "string", "createCDATASection");
					return null;
				}
			return createCDATASection(tmp1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object createCDATASection(object instance, PhpStack stack)
		{
			stack.CalleeName = "createCDATASection";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).createCDATASection(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object createProcessingInstruction(ScriptContext __context, object target, object data)
		{
			
			string tmp1 = PhpVariable.AsString(target);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(target, "string", "createProcessingInstruction");
					return null;
				}
			
			string tmp2 = PhpVariable.AsString(data);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(data, "string", "createProcessingInstruction");
					return null;
				}
			return createProcessingInstruction(tmp1, tmp2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object createProcessingInstruction(object instance, PhpStack stack)
		{
			stack.CalleeName = "createProcessingInstruction";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			stack.RemoveFrame();
			return ((DOMDocument)instance).createProcessingInstruction(stack.Context, arg1, arg2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object createAttribute(ScriptContext __context, object name)
		{
			
			string tmp1 = PhpVariable.AsString(name);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(name, "string", "createAttribute");
					return null;
				}
			return createAttribute(tmp1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object createAttribute(object instance, PhpStack stack)
		{
			stack.CalleeName = "createAttribute";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).createAttribute(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object createEntityReference(ScriptContext __context, object name)
		{
			
			string tmp1 = PhpVariable.AsString(name);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(name, "string", "createEntityReference");
					return null;
				}
			return createEntityReference(tmp1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object createEntityReference(object instance, PhpStack stack)
		{
			stack.CalleeName = "createEntityReference";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).createEntityReference(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object createElementNS(ScriptContext __context, object namespaceUri, object qualifiedName, 		[System.Runtime.InteropServices.OptionalAttribute()]
object value)
		{
			
			string tmp1 = PhpVariable.AsString(namespaceUri);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(namespaceUri, "string", "createElementNS");
					return null;
				}
			
			string tmp2 = PhpVariable.AsString(qualifiedName);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(qualifiedName, "string", "createElementNS");
					return null;
				}
			
			string tmp3 = null;
			if (value != Arg.Default)

				{
					tmp3 = PhpVariable.AsString(value);
					if (tmp3 == null)

						{
							PhpException.InvalidImplicitCast(value, "string", "createElementNS");
							return null;
						}
				}
			return createElementNS(tmp1, tmp2, tmp3);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object createElementNS(object instance, PhpStack stack)
		{
			stack.CalleeName = "createElementNS";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			
			object arg3 = stack.PeekValueOptional(3);
			stack.RemoveFrame();
			return ((DOMDocument)instance).createElementNS(stack.Context, arg1, arg2, arg3);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object createAttributeNS(ScriptContext __context, object namespaceUri, object qualifiedName)
		{
			
			string tmp1 = PhpVariable.AsString(namespaceUri);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(namespaceUri, "string", "createAttributeNS");
					return null;
				}
			
			string tmp2 = PhpVariable.AsString(qualifiedName);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(qualifiedName, "string", "createAttributeNS");
					return null;
				}
			return createAttributeNS(tmp1, tmp2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object createAttributeNS(object instance, PhpStack stack)
		{
			stack.CalleeName = "createAttributeNS";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			stack.RemoveFrame();
			return ((DOMDocument)instance).createAttributeNS(stack.Context, arg1, arg2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object getElementsByTagName(ScriptContext __context, object name)
		{
			
			string tmp1 = PhpVariable.AsString(name);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(name, "string", "getElementsByTagName");
					return null;
				}
			return getElementsByTagName(tmp1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object getElementsByTagName(object instance, PhpStack stack)
		{
			stack.CalleeName = "getElementsByTagName";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).getElementsByTagName(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object getElementsByTagNameNS(ScriptContext __context, object namespaceUri, object localName)
		{
			
			string tmp1 = PhpVariable.AsString(namespaceUri);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(namespaceUri, "string", "getElementsByTagNameNS");
					return null;
				}
			
			string tmp2 = PhpVariable.AsString(localName);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(localName, "string", "getElementsByTagNameNS");
					return null;
				}
			return getElementsByTagNameNS(tmp1, tmp2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object getElementsByTagNameNS(object instance, PhpStack stack)
		{
			stack.CalleeName = "getElementsByTagNameNS";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			stack.RemoveFrame();
			return ((DOMDocument)instance).getElementsByTagNameNS(stack.Context, arg1, arg2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object getElementById(ScriptContext __context, object elementId)
		{
			
			string tmp1 = PhpVariable.AsString(elementId);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(elementId, "string", "getElementById");
					return null;
				}
			getElementById(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object getElementById(object instance, PhpStack stack)
		{
			stack.CalleeName = "getElementById";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).getElementById(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object importNode(ScriptContext __context, object importedNode, object deep)
		{
			
			DOMNode tmp1 = importedNode as DOMNode;
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(importedNode, "DOMNode", "importNode");
					return null;
				}
			if (!(deep is bool))

				{
					PhpException.InvalidImplicitCast(deep, "bool", "importNode");
					return null;
				}
			return importNode(tmp1, (bool)deep);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object importNode(object instance, PhpStack stack)
		{
			stack.CalleeName = "importNode";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			stack.RemoveFrame();
			return ((DOMDocument)instance).importNode(stack.Context, arg1, arg2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object adoptNode(ScriptContext __context, object source)
		{
			
			DOMNode tmp1 = source as DOMNode;
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(source, "DOMNode", "adoptNode");
					return null;
				}
			adoptNode(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object adoptNode(object instance, PhpStack stack)
		{
			stack.CalleeName = "adoptNode";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).adoptNode(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object normalizeDocument(ScriptContext __context)
		{
			normalizeDocument();
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object normalizeDocument(object instance, PhpStack stack)
		{
			stack.CalleeName = "normalizeDocument";
			stack.RemoveFrame();
			return ((DOMDocument)instance).normalizeDocument(stack.Context);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object renameNode(ScriptContext __context, object node, object namespaceUri, object qualifiedName)
		{
			
			DOMNode tmp1 = node as DOMNode;
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(node, "DOMNode", "renameNode");
					return null;
				}
			
			string tmp2 = PhpVariable.AsString(namespaceUri);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(namespaceUri, "string", "renameNode");
					return null;
				}
			
			string tmp3 = PhpVariable.AsString(qualifiedName);
			if (tmp3 == null)

				{
					PhpException.InvalidImplicitCast(qualifiedName, "string", "renameNode");
					return null;
				}
			renameNode(tmp1, tmp2, tmp3);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object renameNode(object instance, PhpStack stack)
		{
			stack.CalleeName = "renameNode";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValue(2);
			
			object arg3 = stack.PeekValue(3);
			stack.RemoveFrame();
			return ((DOMDocument)instance).renameNode(stack.Context, arg1, arg2, arg3);
		}
		public static object load(ScriptContext __context, object instance, object fileName, 		[System.Runtime.InteropServices.OptionalAttribute()]
object options)
		{
			
			DOMDocument tmp1 = instance as DOMDocument;
			if (tmp1 == null && instance != null)

				{
					PhpException.InvalidImplicitCast(instance, "DOMDocument", "load");
					return null;
				}
			
			string tmp2 = PhpVariable.AsString(fileName);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(fileName, "string", "load");
					return null;
				}
			
			int tmp3;
			if (options != Arg.Default)

				{
					if (!(options is int))

						{
							PhpException.InvalidImplicitCast(options, "int", "load");
							return null;
						}
					tmp3 = (int)options;
				}
			else
tmp3 = new int();
			return load(tmp1, tmp2, tmp3);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object load(ScriptContext __context, object fileName, 		[System.Runtime.InteropServices.OptionalAttribute()]
object options)
		{
			
			string tmp2 = PhpVariable.AsString(fileName);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(fileName, "string", "load");
					return null;
				}
			
			int tmp3;
			if (options != Arg.Default)

				{
					if (!(options is int))

						{
							PhpException.InvalidImplicitCast(options, "int", "load");
							return null;
						}
					tmp3 = (int)options;
				}
			else
tmp3 = new int();
			return load(null, tmp2, tmp3);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object load(object instance, PhpStack stack)
		{
			stack.CalleeName = "load";
			
			object arg1 = instance;
			
			object arg2 = stack.PeekValue(1);
			
			object arg3 = stack.PeekValueOptional(2);
			stack.RemoveFrame();
			return load(stack.Context, arg1, arg2, arg3);
		}
		public static object loadXML(ScriptContext __context, object instance, object xmlString, 		[System.Runtime.InteropServices.OptionalAttribute()]
object options)
		{
			
			DOMDocument tmp1 = instance as DOMDocument;
			if (tmp1 == null && instance != null)

				{
					PhpException.InvalidImplicitCast(instance, "DOMDocument", "loadXML");
					return null;
				}
			
			string tmp2 = PhpVariable.AsString(xmlString);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(xmlString, "string", "loadXML");
					return null;
				}
			
			int tmp3;
			if (options != Arg.Default)

				{
					if (!(options is int))

						{
							PhpException.InvalidImplicitCast(options, "int", "loadXML");
							return null;
						}
					tmp3 = (int)options;
				}
			else
tmp3 = new int();
			return loadXML(tmp1, tmp2, tmp3);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object loadXML(ScriptContext __context, object xmlString, 		[System.Runtime.InteropServices.OptionalAttribute()]
object options)
		{
			
			string tmp2 = PhpVariable.AsString(xmlString);
			if (tmp2 == null)

				{
					PhpException.InvalidImplicitCast(xmlString, "string", "loadXML");
					return null;
				}
			
			int tmp3;
			if (options != Arg.Default)

				{
					if (!(options is int))

						{
							PhpException.InvalidImplicitCast(options, "int", "loadXML");
							return null;
						}
					tmp3 = (int)options;
				}
			else
tmp3 = new int();
			return loadXML(null, tmp2, tmp3);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object loadXML(object instance, PhpStack stack)
		{
			stack.CalleeName = "loadXML";
			
			object arg1 = instance;
			
			object arg2 = stack.PeekValue(1);
			
			object arg3 = stack.PeekValueOptional(2);
			stack.RemoveFrame();
			return loadXML(stack.Context, arg1, arg2, arg3);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object save(ScriptContext __context, object fileName, 		[System.Runtime.InteropServices.OptionalAttribute()]
object options)
		{
			
			string tmp1 = PhpVariable.AsString(fileName);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(fileName, "string", "save");
					return null;
				}
			
			int tmp2;
			if (options != Arg.Default)

				{
					if (!(options is int))

						{
							PhpException.InvalidImplicitCast(options, "int", "save");
							return null;
						}
					tmp2 = (int)options;
				}
			else
tmp2 = new int();
			return save(tmp1, tmp2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object save(object instance, PhpStack stack)
		{
			stack.CalleeName = "save";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValueOptional(2);
			stack.RemoveFrame();
			return ((DOMDocument)instance).save(stack.Context, arg1, arg2);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object saveXML(ScriptContext __context, 		[System.Runtime.InteropServices.OptionalAttribute()]
object node)
		{
			
			DOMNode tmp1 = null;
			if (node != Arg.Default)

				{
					tmp1 = node as DOMNode;
					if (tmp1 == null)

						{
							PhpException.InvalidImplicitCast(node, "DOMNode", "saveXML");
							return null;
						}
				}
			return saveXML(tmp1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object saveXML(object instance, PhpStack stack)
		{
			stack.CalleeName = "saveXML";
			
			object arg1 = stack.PeekValueOptional(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).saveXML(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object loadHTML(ScriptContext __context, object source)
		{
			
			string tmp1 = PhpVariable.AsString(source);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(source, "string", "loadHTML");
					return null;
				}
			loadHTML(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object loadHTML(object instance, PhpStack stack)
		{
			stack.CalleeName = "loadHTML";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).loadHTML(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object loadHTMLFile(ScriptContext __context, object source)
		{
			
			string tmp1 = PhpVariable.AsString(source);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(source, "string", "loadHTMLFile");
					return null;
				}
			loadHTMLFile(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object loadHTMLFile(object instance, PhpStack stack)
		{
			stack.CalleeName = "loadHTMLFile";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).loadHTMLFile(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object saveHTML(ScriptContext __context)
		{
			saveHTML();
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object saveHTML(object instance, PhpStack stack)
		{
			stack.CalleeName = "saveHTML";
			stack.RemoveFrame();
			return ((DOMDocument)instance).saveHTML(stack.Context);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object saveHTMLFile(ScriptContext __context, object file)
		{
			
			string tmp1 = PhpVariable.AsString(file);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(file, "string", "saveHTMLFile");
					return null;
				}
			saveHTMLFile(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object saveHTMLFile(object instance, PhpStack stack)
		{
			stack.CalleeName = "saveHTMLFile";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).saveHTMLFile(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object xinclude(ScriptContext __context, 		[System.Runtime.InteropServices.OptionalAttribute()]
object options)
		{
			
			int tmp1;
			if (options != Arg.Default)

				{
					if (!(options is int))

						{
							PhpException.InvalidImplicitCast(options, "int", "xinclude");
							return null;
						}
					tmp1 = (int)options;
				}
			else
tmp1 = new int();
			xinclude(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object xinclude(object instance, PhpStack stack)
		{
			stack.CalleeName = "xinclude";
			
			object arg1 = stack.PeekValueOptional(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).xinclude(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object validate(ScriptContext __context)
		{
			validate();
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object validate(object instance, PhpStack stack)
		{
			stack.CalleeName = "validate";
			stack.RemoveFrame();
			return ((DOMDocument)instance).validate(stack.Context);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object schemaValidate(ScriptContext __context, object schemaFile)
		{
			
			string tmp1 = PhpVariable.AsString(schemaFile);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(schemaFile, "string", "schemaValidate");
					return null;
				}
			return schemaValidate(tmp1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object schemaValidate(object instance, PhpStack stack)
		{
			stack.CalleeName = "schemaValidate";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).schemaValidate(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object schemaValidateSource(ScriptContext __context, object schemaString)
		{
			
			string tmp1 = PhpVariable.AsString(schemaString);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(schemaString, "string", "schemaValidateSource");
					return null;
				}
			return schemaValidateSource(tmp1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object schemaValidateSource(object instance, PhpStack stack)
		{
			stack.CalleeName = "schemaValidateSource";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).schemaValidateSource(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object relaxNGValidate(ScriptContext __context, object schemaFile)
		{
			
			string tmp1 = PhpVariable.AsString(schemaFile);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(schemaFile, "string", "relaxNGValidate");
					return null;
				}
			relaxNGValidate(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object relaxNGValidate(object instance, PhpStack stack)
		{
			stack.CalleeName = "relaxNGValidate";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).relaxNGValidate(stack.Context, arg1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object relaxNGValidateSource(ScriptContext __context, object schema)
		{
			
			string tmp1 = PhpVariable.AsString(schema);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(schema, "string", "relaxNGValidateSource");
					return null;
				}
			relaxNGValidateSource(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object relaxNGValidateSource(object instance, PhpStack stack)
		{
			stack.CalleeName = "relaxNGValidateSource";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocument)instance).relaxNGValidateSource(stack.Context, arg1);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("nodeName", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_nodeName), null);
			desc.AddProperty("nodeValue", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_nodeValue), new SetterDelegate(DOMDocument.__set_nodeValue));
			desc.AddProperty("nodeType", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_nodeType), null);
			desc.AddProperty("doctype", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_doctype), null);
			desc.AddProperty("implementation", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_implementation), null);
			desc.AddProperty("documentElement", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_documentElement), null);
			desc.AddProperty("actualEncoding", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_actualEncoding), null);
			desc.AddProperty("xmlEncoding", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_xmlEncoding), null);
			desc.AddProperty("encoding", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_encoding), new SetterDelegate(DOMDocument.__set_encoding));
			desc.AddProperty("xmlStandalone", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_xmlStandalone), new SetterDelegate(DOMDocument.__set_xmlStandalone));
			desc.AddProperty("standalone", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_standalone), new SetterDelegate(DOMDocument.__set_standalone));
			desc.AddProperty("xmlVersion", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_xmlVersion), new SetterDelegate(DOMDocument.__set_xmlVersion));
			desc.AddProperty("version", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_version), new SetterDelegate(DOMDocument.__set_version));
			desc.AddProperty("strictErrorChecking", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_strictErrorChecking), new SetterDelegate(DOMDocument.__set_strictErrorChecking));
			desc.AddProperty("documentURI", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_documentURI), new SetterDelegate(DOMDocument.__set_documentURI));
			desc.AddProperty("config", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_config), null);
			desc.AddProperty("formatOutput", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_formatOutput), new SetterDelegate(DOMDocument.__set_formatOutput));
			desc.AddProperty("validateOnParse", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_validateOnParse), new SetterDelegate(DOMDocument.__set_validateOnParse));
			desc.AddProperty("resolveExternals", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_resolveExternals), new SetterDelegate(DOMDocument.__set_resolveExternals));
			desc.AddProperty("preserveWhiteSpace", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_preserveWhiteSpace), new SetterDelegate(DOMDocument.__set_preserveWhiteSpace));
			desc.AddProperty("recover", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_recover), new SetterDelegate(DOMDocument.__set_recover));
			desc.AddProperty("substituteEntities", PhpMemberAttributes.Public, new GetterDelegate(DOMDocument.__get_substituteEntities), new SetterDelegate(DOMDocument.__set_substituteEntities));
			desc.AddMethod("__construct", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.__construct));
			desc.AddMethod("createElement", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.createElement));
			desc.AddMethod("createDocumentFragment", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.createDocumentFragment));
			desc.AddMethod("createTextNode", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.createTextNode));
			desc.AddMethod("createComment", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.createComment));
			desc.AddMethod("createCDATASection", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.createCDATASection));
			desc.AddMethod("createProcessingInstruction", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.createProcessingInstruction));
			desc.AddMethod("createAttribute", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.createAttribute));
			desc.AddMethod("createEntityReference", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.createEntityReference));
			desc.AddMethod("createElementNS", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.createElementNS));
			desc.AddMethod("createAttributeNS", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.createAttributeNS));
			desc.AddMethod("getElementsByTagName", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.getElementsByTagName));
			desc.AddMethod("getElementsByTagNameNS", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.getElementsByTagNameNS));
			desc.AddMethod("getElementById", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.getElementById));
			desc.AddMethod("importNode", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.importNode));
			desc.AddMethod("adoptNode", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.adoptNode));
			desc.AddMethod("normalizeDocument", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.normalizeDocument));
			desc.AddMethod("renameNode", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.renameNode));
			desc.AddMethod("load", PhpMemberAttributes.Public | PhpMemberAttributes.Static, new RoutineDelegate(DOMDocument.load));
			desc.AddMethod("loadXML", PhpMemberAttributes.Public | PhpMemberAttributes.Static, new RoutineDelegate(DOMDocument.loadXML));
			desc.AddMethod("save", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.save));
			desc.AddMethod("saveXML", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.saveXML));
			desc.AddMethod("loadHTML", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.loadHTML));
			desc.AddMethod("loadHTMLFile", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.loadHTMLFile));
			desc.AddMethod("saveHTML", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.saveHTML));
			desc.AddMethod("saveHTMLFile", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.saveHTMLFile));
			desc.AddMethod("xinclude", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.xinclude));
			desc.AddMethod("validate", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.validate));
			desc.AddMethod("schemaValidate", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.schemaValidate));
			desc.AddMethod("schemaValidateSource", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.schemaValidateSource));
			desc.AddMethod("relaxNGValidate", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.relaxNGValidate));
			desc.AddMethod("relaxNGValidateSource", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocument.relaxNGValidateSource));
		}
	}
	[Serializable()]
	public partial class DOMDocumentFragment
	{
		protected DOMDocumentFragment(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMDocumentFragment(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMDocumentFragment(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_nodeName(object instance)
		{
			return ((DOMDocumentFragment)instance).nodeName;
		}
		private static object __get_nodeValue(object instance)
		{
			return ((DOMDocumentFragment)instance).nodeValue;
		}
		private static void __set_nodeValue(object instance, object value)
		{
			((DOMDocumentFragment)instance).nodeValue = value;
		}
		private static object __get_namespaceURI(object instance)
		{
			return ((DOMDocumentFragment)instance).namespaceURI;
		}
		private static object __get_nodeType(object instance)
		{
			return ((DOMDocumentFragment)instance).nodeType;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __construct(ScriptContext __context)
		{
			__construct();
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __construct(object instance, PhpStack stack)
		{
			stack.CalleeName = "__construct";
			stack.RemoveFrame();
			return ((DOMDocumentFragment)instance).__construct(stack.Context);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object appendXML(ScriptContext __context, object data)
		{
			
			string tmp1 = PhpVariable.AsString(data);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(data, "string", "appendXML");
					return null;
				}
			return appendXML(tmp1);
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object appendXML(object instance, PhpStack stack)
		{
			stack.CalleeName = "appendXML";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMDocumentFragment)instance).appendXML(stack.Context, arg1);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("nodeName", PhpMemberAttributes.Public, new GetterDelegate(DOMDocumentFragment.__get_nodeName), null);
			desc.AddProperty("nodeValue", PhpMemberAttributes.Public, new GetterDelegate(DOMDocumentFragment.__get_nodeValue), new SetterDelegate(DOMDocumentFragment.__set_nodeValue));
			desc.AddProperty("namespaceURI", PhpMemberAttributes.Public, new GetterDelegate(DOMDocumentFragment.__get_namespaceURI), null);
			desc.AddProperty("nodeType", PhpMemberAttributes.Public, new GetterDelegate(DOMDocumentFragment.__get_nodeType), null);
			desc.AddMethod("__construct", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocumentFragment.__construct));
			desc.AddMethod("appendXML", PhpMemberAttributes.Public, new RoutineDelegate(DOMDocumentFragment.appendXML));
		}
	}
}
