// ***
// Do not edit this file. It has been generated by the ClassDynamizer tool.
// ***
#pragma warning disable 0108
using PHP.Core.Reflection;
using System;
using System.Xml;
using System.Xml.Schema;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using PHP.Core;
namespace PHP.Library.Xml
{
	[Serializable()]
	public partial class DOMEntity
	{
		protected DOMEntity(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMEntity(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMEntity(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_nodeType(object instance)
		{
			return ((DOMEntity)instance).nodeType;
		}
		private static object __get_publicId(object instance)
		{
			return ((DOMEntity)instance).publicId;
		}
		private static object __get_systemId(object instance)
		{
			return ((DOMEntity)instance).systemId;
		}
		private static object __get_notationName(object instance)
		{
			return ((DOMEntity)instance).notationName;
		}
		private static object __get_actualEncoding(object instance)
		{
			return ((DOMEntity)instance).actualEncoding;
		}
		private static void __set_actualEncoding(object instance, object value)
		{
			
			string tmp1 = PhpVariable.AsString(value);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(value, "string", "actualEncoding");
					return;
				}
			((DOMEntity)instance).actualEncoding = tmp1;
		}
		private static object __get_encoding(object instance)
		{
			return ((DOMEntity)instance).encoding;
		}
		private static void __set_encoding(object instance, object value)
		{
			
			string tmp1 = PhpVariable.AsString(value);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(value, "string", "encoding");
					return;
				}
			((DOMEntity)instance).encoding = tmp1;
		}
		private static object __get_version(object instance)
		{
			return ((DOMEntity)instance).version;
		}
		private static void __set_version(object instance, object value)
		{
			
			string tmp1 = PhpVariable.AsString(value);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(value, "string", "version");
					return;
				}
			((DOMEntity)instance).version = tmp1;
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("nodeType", PhpMemberAttributes.Public, new GetterDelegate(DOMEntity.__get_nodeType), null);
			desc.AddProperty("publicId", PhpMemberAttributes.Public, new GetterDelegate(DOMEntity.__get_publicId), null);
			desc.AddProperty("systemId", PhpMemberAttributes.Public, new GetterDelegate(DOMEntity.__get_systemId), null);
			desc.AddProperty("notationName", PhpMemberAttributes.Public, new GetterDelegate(DOMEntity.__get_notationName), null);
			desc.AddProperty("actualEncoding", PhpMemberAttributes.Public, new GetterDelegate(DOMEntity.__get_actualEncoding), new SetterDelegate(DOMEntity.__set_actualEncoding));
			desc.AddProperty("encoding", PhpMemberAttributes.Public, new GetterDelegate(DOMEntity.__get_encoding), new SetterDelegate(DOMEntity.__set_encoding));
			desc.AddProperty("version", PhpMemberAttributes.Public, new GetterDelegate(DOMEntity.__get_version), new SetterDelegate(DOMEntity.__set_version));
		}
	}
	[Serializable()]
	public partial class DOMEntityReference
	{
		protected DOMEntityReference(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMEntityReference(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMEntityReference(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_nodeName(object instance)
		{
			return ((DOMEntityReference)instance).nodeName;
		}
		private static object __get_nodeValue(object instance)
		{
			return ((DOMEntityReference)instance).nodeValue;
		}
		private static void __set_nodeValue(object instance, object value)
		{
			((DOMEntityReference)instance).nodeValue = value;
		}
		private static object __get_namespaceURI(object instance)
		{
			return ((DOMEntityReference)instance).namespaceURI;
		}
		private static object __get_nodeType(object instance)
		{
			return ((DOMEntityReference)instance).nodeType;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __construct(ScriptContext __context, object name)
		{
			
			string tmp1 = PhpVariable.AsString(name);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(name, "string", "__construct");
					return null;
				}
			__construct(tmp1);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __construct(object instance, PhpStack stack)
		{
			stack.CalleeName = "__construct";
			
			object arg1 = stack.PeekValue(1);
			stack.RemoveFrame();
			return ((DOMEntityReference)instance).__construct(stack.Context, arg1);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("nodeName", PhpMemberAttributes.Public, new GetterDelegate(DOMEntityReference.__get_nodeName), null);
			desc.AddProperty("nodeValue", PhpMemberAttributes.Public, new GetterDelegate(DOMEntityReference.__get_nodeValue), new SetterDelegate(DOMEntityReference.__set_nodeValue));
			desc.AddProperty("namespaceURI", PhpMemberAttributes.Public, new GetterDelegate(DOMEntityReference.__get_namespaceURI), null);
			desc.AddProperty("nodeType", PhpMemberAttributes.Public, new GetterDelegate(DOMEntityReference.__get_nodeType), null);
			desc.AddMethod("__construct", PhpMemberAttributes.Public, new RoutineDelegate(DOMEntityReference.__construct));
		}
	}
}
