// ***
// Do not edit this file. It has been generated by the ClassDynamizer tool.
// ***
#pragma warning disable 0108
using PHP.Core.Reflection;
using System;
using System.Text;
using System.ComponentModel;
using System.Collections.Generic;
using PHP.Core;
namespace PHP.Library.Xml
{
	[Serializable()]
	public sealed partial class DOMException
	{
		private DOMException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMException(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_code(object instance)
		{
			return ((DOMException)instance).code;
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("code", PhpMemberAttributes.Public, new GetterDelegate(DOMException.__get_code), null);
		}
	}
}
