// ***
// Do not edit this file. It has been generated by the ClassDynamizer tool.
// ***
#pragma warning disable 0108
using PHP.Core.Reflection;
using System;
using System.Xml;
using System.Xml.Schema;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using PHP.Core;
namespace PHP.Library.Xml
{
	[Serializable()]
	public partial class DOMDocumentType
	{
		protected DOMDocumentType(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMDocumentType(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMDocumentType(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_nodeType(object instance)
		{
			return ((DOMDocumentType)instance).nodeType;
		}
		private static object __get_name(object instance)
		{
			return ((DOMDocumentType)instance).name;
		}
		private static object __get_entities(object instance)
		{
			return ((DOMDocumentType)instance).entities;
		}
		private static object __get_notations(object instance)
		{
			return ((DOMDocumentType)instance).notations;
		}
		private static object __get_publicId(object instance)
		{
			return ((DOMDocumentType)instance).publicId;
		}
		private static object __get_systemId(object instance)
		{
			return ((DOMDocumentType)instance).systemId;
		}
		private static object __get_internalSubset(object instance)
		{
			return ((DOMDocumentType)instance).internalSubset;
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("nodeType", PhpMemberAttributes.Public, new GetterDelegate(DOMDocumentType.__get_nodeType), null);
			desc.AddProperty("name", PhpMemberAttributes.Public, new GetterDelegate(DOMDocumentType.__get_name), null);
			desc.AddProperty("entities", PhpMemberAttributes.Public, new GetterDelegate(DOMDocumentType.__get_entities), null);
			desc.AddProperty("notations", PhpMemberAttributes.Public, new GetterDelegate(DOMDocumentType.__get_notations), null);
			desc.AddProperty("publicId", PhpMemberAttributes.Public, new GetterDelegate(DOMDocumentType.__get_publicId), null);
			desc.AddProperty("systemId", PhpMemberAttributes.Public, new GetterDelegate(DOMDocumentType.__get_systemId), null);
			desc.AddProperty("internalSubset", PhpMemberAttributes.Public, new GetterDelegate(DOMDocumentType.__get_internalSubset), null);
		}
	}
	[Serializable()]
	public partial class DOMNotation : PhpObject
	{
		protected DOMNotation(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMNotation(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMNotation(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_publicId(object instance)
		{
			return ((DOMNotation)instance).publicId;
		}
		private static object __get_systemId(object instance)
		{
			return ((DOMNotation)instance).systemId;
		}
		private static object __get_nodeName(object instance)
		{
			return ((DOMNotation)instance).nodeName;
		}
		private static object __get_nodeValue(object instance)
		{
			return ((DOMNotation)instance).nodeValue;
		}
		private static void __set_nodeValue(object instance, object value)
		{
			((DOMNotation)instance).nodeValue = value;
		}
		private static object __get_attributes(object instance)
		{
			return ((DOMNotation)instance).attributes;
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("publicId", PhpMemberAttributes.Public, new GetterDelegate(DOMNotation.__get_publicId), null);
			desc.AddProperty("systemId", PhpMemberAttributes.Public, new GetterDelegate(DOMNotation.__get_systemId), null);
			desc.AddProperty("nodeName", PhpMemberAttributes.Public, new GetterDelegate(DOMNotation.__get_nodeName), null);
			desc.AddProperty("nodeValue", PhpMemberAttributes.Public, new GetterDelegate(DOMNotation.__get_nodeValue), new SetterDelegate(DOMNotation.__set_nodeValue));
			desc.AddProperty("attributes", PhpMemberAttributes.Public, new GetterDelegate(DOMNotation.__get_attributes), null);
		}
	}
	[Serializable()]
	public partial class DOMProcessingInstruction
	{
		protected DOMProcessingInstruction(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMProcessingInstruction(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMProcessingInstruction(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_nodeName(object instance)
		{
			return ((DOMProcessingInstruction)instance).nodeName;
		}
		private static object __get_nodeValue(object instance)
		{
			return ((DOMProcessingInstruction)instance).nodeValue;
		}
		private static void __set_nodeValue(object instance, object value)
		{
			((DOMProcessingInstruction)instance).nodeValue = value;
		}
		private static object __get_namespaceURI(object instance)
		{
			return ((DOMProcessingInstruction)instance).namespaceURI;
		}
		private static object __get_nodeType(object instance)
		{
			return ((DOMProcessingInstruction)instance).nodeType;
		}
		private static object __get_target(object instance)
		{
			return ((DOMProcessingInstruction)instance).target;
		}
		private static object __get_data(object instance)
		{
			return ((DOMProcessingInstruction)instance).data;
		}
		private static void __set_data(object instance, object value)
		{
			((DOMProcessingInstruction)instance).data = value;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public object __construct(ScriptContext __context, object name, 		[System.Runtime.InteropServices.OptionalAttribute()]
object value)
		{
			
			string tmp1 = PhpVariable.AsString(name);
			if (tmp1 == null)

				{
					PhpException.InvalidImplicitCast(name, "string", "__construct");
					return null;
				}
			
			string tmp2 = null;
			if (value != Arg.Default)

				{
					tmp2 = PhpVariable.AsString(value);
					if (tmp2 == null)

						{
							PhpException.InvalidImplicitCast(value, "string", "__construct");
							return null;
						}
				}
			__construct(tmp1, tmp2);
			return null;
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public static object __construct(object instance, PhpStack stack)
		{
			stack.CalleeName = "__construct";
			
			object arg1 = stack.PeekValue(1);
			
			object arg2 = stack.PeekValueOptional(2);
			stack.RemoveFrame();
			return ((DOMProcessingInstruction)instance).__construct(stack.Context, arg1, arg2);
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("nodeName", PhpMemberAttributes.Public, new GetterDelegate(DOMProcessingInstruction.__get_nodeName), null);
			desc.AddProperty("nodeValue", PhpMemberAttributes.Public, new GetterDelegate(DOMProcessingInstruction.__get_nodeValue), new SetterDelegate(DOMProcessingInstruction.__set_nodeValue));
			desc.AddProperty("namespaceURI", PhpMemberAttributes.Public, new GetterDelegate(DOMProcessingInstruction.__get_namespaceURI), null);
			desc.AddProperty("nodeType", PhpMemberAttributes.Public, new GetterDelegate(DOMProcessingInstruction.__get_nodeType), null);
			desc.AddProperty("target", PhpMemberAttributes.Public, new GetterDelegate(DOMProcessingInstruction.__get_target), null);
			desc.AddProperty("data", PhpMemberAttributes.Public, new GetterDelegate(DOMProcessingInstruction.__get_data), new SetterDelegate(DOMProcessingInstruction.__set_data));
			desc.AddMethod("__construct", PhpMemberAttributes.Public, new RoutineDelegate(DOMProcessingInstruction.__construct));
		}
	}
	[Serializable()]
	public partial class DOMNameSpaceNode : PhpObject
	{
		protected DOMNameSpaceNode(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMNameSpaceNode(ScriptContext context, bool newInstance) : base(context, newInstance)
		{
		}
		[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
		public DOMNameSpaceNode(ScriptContext context, DTypeDesc caller) : this(context, true)
		{
			this.InvokeConstructor(context, caller);
		}
		private static object __get_nodeName(object instance)
		{
			return ((DOMNameSpaceNode)instance).nodeName;
		}
		private static object __get_nodeValue(object instance)
		{
			return ((DOMNameSpaceNode)instance).nodeValue;
		}
		private static object __get_nodeType(object instance)
		{
			return ((DOMNameSpaceNode)instance).nodeType;
		}
		private static object __get_prefix(object instance)
		{
			return ((DOMNameSpaceNode)instance).prefix;
		}
		private static object __get_namespaceURI(object instance)
		{
			return ((DOMNameSpaceNode)instance).namespaceURI;
		}
		private static object __get_ownerDocument(object instance)
		{
			return ((DOMNameSpaceNode)instance).ownerDocument;
		}
		private static object __get_parentNode(object instance)
		{
			return ((DOMNameSpaceNode)instance).parentNode;
		}
		private static void __PopulateTypeDesc(PhpTypeDesc desc)
		{
			desc.AddProperty("nodeName", PhpMemberAttributes.Public, new GetterDelegate(DOMNameSpaceNode.__get_nodeName), null);
			desc.AddProperty("nodeValue", PhpMemberAttributes.Public, new GetterDelegate(DOMNameSpaceNode.__get_nodeValue), null);
			desc.AddProperty("nodeType", PhpMemberAttributes.Public, new GetterDelegate(DOMNameSpaceNode.__get_nodeType), null);
			desc.AddProperty("prefix", PhpMemberAttributes.Public, new GetterDelegate(DOMNameSpaceNode.__get_prefix), null);
			desc.AddProperty("namespaceURI", PhpMemberAttributes.Public, new GetterDelegate(DOMNameSpaceNode.__get_namespaceURI), null);
			desc.AddProperty("ownerDocument", PhpMemberAttributes.Public, new GetterDelegate(DOMNameSpaceNode.__get_ownerDocument), null);
			desc.AddProperty("parentNode", PhpMemberAttributes.Public, new GetterDelegate(DOMNameSpaceNode.__get_parentNode), null);
		}
	}
}
